package main

import (
	"fmt"
	"regexp"
	"time"

	"github.com/guardianwaf/guardianwaf/internal/layers/apivalidation"
	"github.com/guardianwaf/guardianwaf/internal/layers/clientside"
	"github.com/guardianwaf/guardianwaf/internal/layers/crs"
	"github.com/guardianwaf/guardianwaf/internal/layers/dlp"
	"github.com/guardianwaf/guardianwaf/internal/layers/virtualpatch"
)

func (a *mcpEngineAdapter) GetCRSRules(phase int, severity string) (any, error) {
	layer := a.engine.FindLayer("crs")
	if layer == nil {
		return map[string]any{"enabled": false, "rules": []any{}}, nil
	}
	crsLayer, ok := layer.(*crs.Layer)
	if !ok {
		return map[string]any{"enabled": a.cfg.WAF.CRS.Enabled, "rules": []any{}}, nil
	}
	var rules []*crs.Rule
	if phase > 0 {
		rules = crsLayer.GetRulesByPhase(phase)
	} else {
		rules = crsLayer.GetAllRules()
	}
	filtered := make([]map[string]any, 0, len(rules))
	for _, r := range rules {
		info := map[string]any{
			"id":      r.ID,
			"phase":   r.Phase,
			"enabled": crsLayer.IsRuleEnabled(r.ID),
		}
		if severity != "" && r.Severity != severity {
			continue
		}
		filtered = append(filtered, info)
	}
	return map[string]any{
		"enabled": a.cfg.WAF.CRS.Enabled,
		"rules":   filtered,
	}, nil
}

func (a *mcpEngineAdapter) EnableCRSRule(ruleID string, enabled bool) error {
	layer := a.engine.FindLayer("crs")
	if layer == nil {
		return fmt.Errorf("CRS layer not available")
	}
	crsLayer, ok := layer.(*crs.Layer)
	if !ok {
		return fmt.Errorf("CRS layer type mismatch")
	}
	if enabled {
		crsLayer.EnableRule(ruleID)
	} else {
		crsLayer.DisableRule(ruleID)
	}
	return nil
}

func (a *mcpEngineAdapter) SetParanoiaLevel(level int) error {
	cfg := a.engine.Config()
	cfg.WAF.CRS.ParanoiaLevel = level
	return a.engine.Reload(cfg)
}

func (a *mcpEngineAdapter) AddCRSExclusion(ruleID, path, parameter, reason string) error {
	layer := a.engine.FindLayer("crs")
	if layer == nil {
		return fmt.Errorf("CRS layer not available")
	}
	crsLayer, ok := layer.(*crs.Layer)
	if !ok {
		return fmt.Errorf("CRS layer type mismatch")
	}
	crsLayer.DisableRule(ruleID)
	cfg := a.engine.Config()
	cfg.WAF.CRS.DisabledRules = append(cfg.WAF.CRS.DisabledRules, ruleID)
	return a.engine.Reload(cfg)
}

func (a *mcpEngineAdapter) GetVirtualPatches(severity string, activeOnly bool) (any, error) {
	layer := a.engine.FindLayer("virtualpatch")
	if layer == nil {
		return map[string]any{"enabled": false, "patches": []any{}}, nil
	}
	vpLayer, ok := layer.(*virtualpatch.Layer)
	if !ok {
		return map[string]any{"enabled": a.cfg.WAF.VirtualPatch.Enabled, "patches": []any{}}, nil
	}
	var patches []virtualpatch.VirtualPatch
	if activeOnly {
		patches = vpLayer.GetActivePatches()
	} else {
		patches = vpLayer.GetAllPatches()
	}
	filtered := make([]map[string]any, 0, len(patches))
	for _, p := range patches {
		if severity != "" && p.Severity != severity {
			continue
		}
		filtered = append(filtered, map[string]any{
			"id":             p.ID,
			"cve_id":         p.CVEID,
			"name":           p.Name,
			"severity":       p.Severity,
			"action":         p.Action,
			"score":          p.Score,
			"enabled":        p.Enabled,
			"hits":           p.Hits,
			"auto_generated": p.AutoGenerated,
			"review_status":  p.ReviewStatus,
			"provenance":     p.Provenance,
			"reviewed_by":    p.ReviewedBy,
			"applied_by":     p.AppliedBy,
		})
	}
	return map[string]any{
		"enabled": a.cfg.WAF.VirtualPatch.Enabled,
		"patches": filtered,
	}, nil
}

func (a *mcpEngineAdapter) EnableVirtualPatch(patchID string, enabled bool) error {
	layer := a.engine.FindLayer("virtualpatch")
	if layer == nil {
		return fmt.Errorf("virtual patch layer not available")
	}
	vpLayer, ok := layer.(*virtualpatch.Layer)
	if !ok {
		return fmt.Errorf("virtual patch layer type mismatch")
	}
	if enabled {
		if !vpLayer.EnablePatchBy(patchID, "mcp") {
			return fmt.Errorf("patch %q not found", patchID)
		}
	} else {
		if !vpLayer.DisablePatchBy(patchID, "mcp") {
			return fmt.Errorf("patch %q not found", patchID)
		}
	}
	return nil
}

func (a *mcpEngineAdapter) AddCustomPatch(id, name, description, cveID, pattern, patternType, target, action, severity string, score int) error {
	layer := a.engine.FindLayer("virtualpatch")
	if layer == nil {
		return fmt.Errorf("virtual patch layer not available")
	}
	vpLayer, ok := layer.(*virtualpatch.Layer)
	if !ok {
		return fmt.Errorf("virtual patch layer type mismatch")
	}
	patch := &virtualpatch.VirtualPatch{
		ID:          id,
		CVEID:       cveID,
		Name:        name,
		Description: description,
		GeneratedAt: time.Now(),
		Patterns: []virtualpatch.PatchPattern{
			{
				Type:      target,
				Pattern:   pattern,
				MatchType: patternType,
			},
		},
		Action:        action,
		Score:         score,
		Severity:      severity,
		Enabled:       true,
		AutoGenerated: false,
		Provenance:    "mcp:manual",
	}
	vpLayer.AddPatch(patch)
	return nil
}

func (a *mcpEngineAdapter) UpdateCVEDatabase() error {
	layer := a.engine.FindLayer("virtualpatch")
	if layer == nil {
		return fmt.Errorf("virtual patch layer not available")
	}
	vpLayer, ok := layer.(*virtualpatch.Layer)
	if !ok {
		return fmt.Errorf("virtual patch layer type mismatch")
	}
	return vpLayer.TriggerUpdate()
}

func (a *mcpEngineAdapter) GetAPISchemas() (any, error) {
	layer := a.engine.FindLayer("apivalidation")
	if layer == nil {
		return map[string]any{"enabled": false, "schemas": []any{}}, nil
	}
	apiLayer, ok := layer.(*apivalidation.Layer)
	if !ok {
		return map[string]any{"enabled": a.cfg.WAF.APIValidation.Enabled, "schemas": []any{}}, nil
	}
	specs := apiLayer.GetSpecs()
	schemaList := make([]map[string]any, 0, len(specs))
	for _, spec := range specs {
		schemaList = append(schemaList, map[string]any{
			"path":       spec.Source.Path,
			"type":       spec.Source.Type,
			"auto_learn": spec.Source.AutoLearn,
		})
	}
	return map[string]any{
		"enabled": a.cfg.WAF.APIValidation.Enabled,
		"schemas": schemaList,
	}, nil
}

func (a *mcpEngineAdapter) UploadAPISchema(name, content, format string, strictMode bool) error {
	layer := a.engine.FindLayer("apivalidation")
	if layer == nil {
		return fmt.Errorf("API validation layer not available")
	}
	apiLayer, ok := layer.(*apivalidation.Layer)
	if !ok {
		return fmt.Errorf("API validation layer type mismatch")
	}
	schemaType := "openapi"
	if format != "" {
		schemaType = format
	}
	return apiLayer.LoadSchema(apivalidation.SchemaSource{
		Path: name,
		Type: schemaType,
	})
}

func (a *mcpEngineAdapter) RemoveAPISchema(name string) error {
	layer := a.engine.FindLayer("apivalidation")
	if layer == nil {
		return fmt.Errorf("API validation layer not available")
	}
	apiLayer, ok := layer.(*apivalidation.Layer)
	if !ok {
		return fmt.Errorf("API validation layer type mismatch")
	}
	if !apiLayer.RemoveSchema(name) {
		return fmt.Errorf("schema %q not found", name)
	}
	return nil
}

func (a *mcpEngineAdapter) SetAPIValidationMode(validateRequest, validateResponse, strictMode, blockOnViolation *bool) error {
	cfg := a.engine.Config()
	if validateRequest != nil {
		cfg.WAF.APIValidation.ValidateRequest = *validateRequest
	}
	if validateResponse != nil {
		cfg.WAF.APIValidation.ValidateResponse = *validateResponse
	}
	if strictMode != nil {
		cfg.WAF.APIValidation.StrictMode = *strictMode
	}
	if blockOnViolation != nil {
		cfg.WAF.APIValidation.BlockOnViolation = *blockOnViolation
	}
	return a.engine.Reload(cfg)
}

func (a *mcpEngineAdapter) TestAPISchema(method, path, body string) (any, error) {
	layer := a.engine.FindLayer("apivalidation")
	if layer == nil {
		return map[string]any{"valid": true, "violations": []any{}}, nil
	}
	apiLayer, ok := layer.(*apivalidation.Layer)
	if !ok {
		return map[string]any{"valid": true, "violations": []any{}}, nil
	}
	route := apiLayer.GetRoute(method, path)
	if route == nil {
		return map[string]any{
			"valid":      false,
			"violations": []any{map[string]any{"message": "no route found for " + method + " " + path}},
		}, nil
	}
	return map[string]any{
		"valid":      true,
		"violations": []any{},
		"route":      route,
	}, nil
}

func (a *mcpEngineAdapter) GetClientSideStats() (any, error) {
	layer := a.engine.FindLayer("clientside")
	stats := map[string]any{
		"enabled":            a.cfg.WAF.ClientSide.Enabled,
		"mode":               a.cfg.WAF.ClientSide.Mode,
		"magecart_detection": a.cfg.WAF.ClientSide.MagecartDetection.Enabled,
		"agent_injection":    a.cfg.WAF.ClientSide.AgentInjection.Enabled,
		"csp_enabled":        a.cfg.WAF.ClientSide.CSP.Enabled,
	}
	if layer != nil {
		if csLayer, ok := layer.(*clientside.Layer); ok {
			csStats := csLayer.GetStats()
			stats["scanned_responses"] = csStats.ScannedResponses
			stats["threats_detected"] = csStats.ThreatsDetected
			stats["scripts_injected"] = csStats.ScriptsInjected
			stats["csp_enforced"] = csStats.CSPEnforced
			stats["blocked_requests"] = csStats.BlockedRequests
		}
	}
	return stats, nil
}

func (a *mcpEngineAdapter) SetClientSideMode(mode string, magecartDetection, agentInjection, cspEnabled *bool) error {
	cfg := a.engine.Config()
	cfg.WAF.ClientSide.Mode = mode
	if magecartDetection != nil {
		cfg.WAF.ClientSide.MagecartDetection.Enabled = *magecartDetection
	}
	if agentInjection != nil {
		cfg.WAF.ClientSide.AgentInjection.Enabled = *agentInjection
	}
	if cspEnabled != nil {
		cfg.WAF.ClientSide.CSP.Enabled = *cspEnabled
	}
	return a.engine.Reload(cfg)
}

func (a *mcpEngineAdapter) AddSkimmingDomain(domain string) error {
	layer := a.engine.FindLayer("clientside")
	if layer == nil {
		return fmt.Errorf("client-side protection layer not available")
	}
	csLayer, ok := layer.(*clientside.Layer)
	if !ok {
		return fmt.Errorf("client-side layer type mismatch")
	}
	csLayer.AddSkimmingDomain(domain)
	return nil
}

func (a *mcpEngineAdapter) GetCSPReports(limit int) (any, error) {
	return map[string]any{"reports": []any{}}, nil
}

func (a *mcpEngineAdapter) GetDLPAlerts(limit int, patternType string) (any, error) {
	return map[string]any{
		"enabled": a.cfg.WAF.DLP.Enabled,
		"alerts":  []any{},
	}, nil
}

func (a *mcpEngineAdapter) AddDLPPattern(id, name, pattern, description, action string, score int) error {
	layer := a.engine.FindLayer("dlp")
	if layer == nil {
		return fmt.Errorf("DLP layer not available")
	}
	dlpLayer, ok := layer.(*dlp.Layer)
	if !ok {
		return fmt.Errorf("DLP layer type mismatch")
	}
	re, err := regexp.Compile(pattern)
	if err != nil {
		return fmt.Errorf("invalid regex pattern: %w", err)
	}
	severity := dlp.SeverityMedium
	switch action {
	case "block":
		severity = dlp.SeverityHigh
	case "log":
		severity = dlp.SeverityLow
	}
	dlpLayer.AddCustomPattern(id, &dlp.Pattern{
		Type:       dlp.PatternCustom,
		Name:       name,
		Regex:      re,
		Severity:   severity,
		Enabled:    true,
		MaskFormat: "***MASKED***",
	})
	return nil
}

func (a *mcpEngineAdapter) RemoveDLPPattern(id string) error {
	layer := a.engine.FindLayer("dlp")
	if layer == nil {
		return fmt.Errorf("DLP layer not available")
	}
	dlpLayer, ok := layer.(*dlp.Layer)
	if !ok {
		return fmt.Errorf("DLP layer type mismatch")
	}
	registry := dlpLayer.GetRegistry()
	if !registry.RemoveCustomPattern(id) {
		return fmt.Errorf("DLP pattern %q not found", id)
	}
	return nil
}

func (a *mcpEngineAdapter) TestDLPPattern(pattern, testData string) (any, error) {
	re, err := regexp.Compile(pattern)
	if err != nil {
		return map[string]any{"error": fmt.Sprintf("invalid regex: %v", err)}, nil
	}
	matches := re.FindAllString(testData, -1)
	return map[string]any{
		"matched": len(matches) > 0,
		"matches": matches,
	}, nil
}

func (a *mcpEngineAdapter) GetHTTP3Status() (any, error) {
	return map[string]any{"enabled": false, "note": "HTTP/3 requires build with -tags http3"}, nil
}

func (a *mcpEngineAdapter) SetHTTP3Config(enabled, enable0RTT, advertiseAltSvc *bool) error {
	return fmt.Errorf("HTTP/3 configuration requires build with -tags http3")
}
