// Package virtualpatch provides virtual patching for known CVEs.
// Automatically generates WAF rules from CVE data for zero-day protection.
package virtualpatch

import (
	"sync"
	"time"
)

// Config holds virtual patching configuration.
type Config struct {
	Enabled           bool          `yaml:"enabled"`
	AutoUpdate        bool          `yaml:"auto_update"`         // Auto-update CVE DB
	UpdateInterval    time.Duration `yaml:"update_interval"`     // Default: 24h
	CVEPath           string        `yaml:"cve_path"`            // Local CVE DB path
	NVDFeedURL        string        `yaml:"nvd_feed_url"`        // NVD API endpoint
	AutoGenerateRules bool          `yaml:"auto_generate_rules"` // Generate rules from CVEs
	BlockSeverity     []string      `yaml:"block_severity"`      // ["CRITICAL", "HIGH"]
	NotifyOnPatch     bool          `yaml:"notify_on_patch"`
	CustomPatches     []CustomPatch `yaml:"custom_patches"` // User-defined patches
}

// DefaultConfig returns default virtual patch configuration.
func DefaultConfig() *Config {
	return &Config{
		Enabled:           false,
		AutoUpdate:        true,
		UpdateInterval:    24 * time.Hour,
		NVDFeedURL:        "https://services.nvd.nist.gov/rest/json/cves/2.0",
		AutoGenerateRules: true,
		BlockSeverity:     []string{"CRITICAL", "HIGH"},
		NotifyOnPatch:     true,
		CustomPatches:     []CustomPatch{},
	}
}

// CVEEntry represents a vulnerability from NVD.
type CVEEntry struct {
	CVEID         string    `json:"cve_id"`
	Description   string    `json:"description"`
	CVSSScore     float64   `json:"cvss_score"`
	Severity      string    `json:"severity"` // CRITICAL, HIGH, MEDIUM, LOW
	CWEs          []string  `json:"cwes"`     // CWE IDs
	PublishedDate time.Time `json:"published_date"`
	ModifiedDate  time.Time `json:"modified_date"`
	VulnStatus    string    `json:"vuln_status"` // Analyzed, Modified, etc.

	// Affected software
	AffectedProducts []Product `json:"affected_products"`

	// Virtual patch rules
	Patches []VirtualPatch `json:"patches"`

	// Metadata
	Source        string `json:"source"` // nvd, custom, community
	AutoGenerated bool   `json:"auto_generated"`
	Active        bool   `json:"active"`
}

// Product represents affected software.
type Product struct {
	Vendor     string `json:"vendor"`
	Product    string `json:"product"`
	Version    string `json:"version"` // affected version range
	CPE        string `json:"cpe"`     // CPE 2.3 format
	Vulnerable bool   `json:"vulnerable"`
}

// VirtualPatch represents a generated WAF rule for a CVE.
type VirtualPatch struct {
	ID          string    `json:"id"`
	CVEID       string    `json:"cve_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	GeneratedAt time.Time `json:"generated_at"`

	// Detection patterns
	Patterns []PatchPattern `json:"patterns"`

	// Actions
	Action   string `json:"action"` // block, log, challenge
	Score    int    `json:"score"`
	Severity string `json:"severity"`

	// Matching criteria
	MatchLogic string `json:"match_logic"` // and, or

	// Status
	Enabled       bool       `json:"enabled"`
	Hits          int64      `json:"hits"` // Match count
	LastHit       *time.Time `json:"last_hit,omitempty"`
	AutoGenerated bool       `json:"auto_generated"`
	ReviewStatus  string     `json:"review_status"` // pending_review, reviewed, applied, disabled
	Provenance    string     `json:"provenance"`    // nvd:auto-generated, dashboard:manual, mcp:manual, config:manual
	ReviewedAt    *time.Time `json:"reviewed_at,omitempty"`
	ReviewedBy    string     `json:"reviewed_by,omitempty"`
	AppliedAt     *time.Time `json:"applied_at,omitempty"`
	AppliedBy     string     `json:"applied_by,omitempty"`
}

// PatchPattern defines a detection pattern.
type PatchPattern struct {
	Type      string `json:"type"`       // path, query, header, body, method, user_agent
	Pattern   string `json:"pattern"`    // Regex or exact match
	MatchType string `json:"match_type"` // regex, exact, contains, starts_with, ends_with
	Key       string `json:"key"`        // For headers/query params (e.g., "X-Api-Version")
	Condition string `json:"condition"`  // and, or (for chaining)
}

// CustomPatch allows user-defined patches.
type CustomPatch struct {
	ID          string `yaml:"id"`
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	CVEID       string `yaml:"cve_id,omitempty"`
	Enabled     bool   `yaml:"enabled"`

	Patterns []PatchPattern `yaml:"patterns"`
	Action   string         `yaml:"action"` // block, log, challenge
	Score    int            `yaml:"score"`
	Severity string         `yaml:"severity"`
}

// Database manages CVE entries and patches.
type Database struct {
	entries   map[string]*CVEEntry     // CVEID -> Entry
	patches   map[string]*VirtualPatch // PatchID -> Patch
	byProduct map[string][]string      // CPE -> []CVEID

	mu sync.RWMutex
}

// NewDatabase creates a new CVE database.
func NewDatabase() *Database {
	return &Database{
		entries:   make(map[string]*CVEEntry),
		patches:   make(map[string]*VirtualPatch),
		byProduct: make(map[string][]string),
	}
}

// AddCVE adds a CVE entry to the database.
func (db *Database) AddCVE(entry *CVEEntry) {
	db.mu.Lock()
	defer db.mu.Unlock()

	for i := range entry.Patches {
		normalizePatchState(&entry.Patches[i])
	}
	db.entries[entry.CVEID] = entry

	// Index by product
	for _, prod := range entry.AffectedProducts {
		cpe := prod.CPE
		if cpe != "" {
			db.byProduct[cpe] = append(db.byProduct[cpe], entry.CVEID)
		}
	}

	// Index patches
	for _, patch := range entry.Patches {
		patchCopy := patch
		db.patches[patch.ID] = &patchCopy
	}
}

// GetCVE retrieves a CVE entry by ID.
func (db *Database) GetCVE(cveID string) *CVEEntry {
	db.mu.RLock()
	defer db.mu.RUnlock()
	return db.entries[cveID]
}

// GetPatch retrieves a patch by ID.
func (db *Database) GetPatch(patchID string) *VirtualPatch {
	db.mu.RLock()
	defer db.mu.RUnlock()

	patch, ok := db.patches[patchID]
	if !ok {
		return nil
	}
	patchCopy := *patch
	return &patchCopy
}

// AddPatch adds or replaces a patch in the database.
func (db *Database) AddPatch(patch *VirtualPatch) {
	if patch == nil {
		return
	}

	db.mu.Lock()
	defer db.mu.Unlock()

	patchCopy := *patch
	normalizePatchState(&patchCopy)
	db.patches[patch.ID] = &patchCopy
}

// SetPatchEnabled updates a patch enabled flag.
func (db *Database) SetPatchEnabled(patchID string, enabled bool) bool {
	return db.SetPatchEnabledBy(patchID, enabled, "system")
}

// SetPatchEnabledBy updates enabled state and records review/apply transition metadata.
func (db *Database) SetPatchEnabledBy(patchID string, enabled bool, actor string) bool {
	db.mu.Lock()
	defer db.mu.Unlock()

	patch, ok := db.patches[patchID]
	if !ok {
		return false
	}
	now := time.Now().UTC()
	if actor == "" {
		actor = "system"
	}
	patch.Enabled = enabled
	if enabled {
		if patch.ReviewStatus == "" || patch.ReviewStatus == "pending_review" {
			patch.ReviewStatus = "reviewed"
			patch.ReviewedAt = &now
			patch.ReviewedBy = actor
		}
		patch.ReviewStatus = "applied"
		patch.AppliedAt = &now
		patch.AppliedBy = actor
	} else if patch.ReviewStatus != "pending_review" {
		patch.ReviewStatus = "disabled"
	}
	return true
}

func normalizePatchState(patch *VirtualPatch) {
	if patch == nil {
		return
	}
	if patch.GeneratedAt.IsZero() {
		patch.GeneratedAt = time.Now().UTC()
	}
	if patch.AutoGenerated {
		if patch.Provenance == "" {
			patch.Provenance = "nvd:auto-generated"
		}
		if patch.ReviewStatus == "" {
			patch.ReviewStatus = "pending_review"
		}
		if patch.ReviewStatus == "pending_review" {
			patch.Enabled = false
		}
		return
	}
	if patch.Provenance == "" {
		patch.Provenance = "config:manual"
	}
	if patch.ReviewStatus == "" {
		if patch.Enabled {
			patch.ReviewStatus = "applied"
			now := patch.GeneratedAt
			patch.ReviewedAt = &now
			patch.AppliedAt = &now
			if patch.ReviewedBy == "" {
				patch.ReviewedBy = "config"
			}
			if patch.AppliedBy == "" {
				patch.AppliedBy = patch.ReviewedBy
			}
		} else {
			patch.ReviewStatus = "disabled"
		}
	}
}

// RecordPatchHit increments hit counters for a patch.
func (db *Database) RecordPatchHit(patchID string, hitAt time.Time) bool {
	db.mu.Lock()
	defer db.mu.Unlock()

	patch, ok := db.patches[patchID]
	if !ok {
		return false
	}
	patch.Hits++
	patch.LastHit = &hitAt
	return true
}

// GetActivePatches returns copies of all active patches (safe for concurrent use).
func (db *Database) GetActivePatches() []VirtualPatch {
	db.mu.RLock()
	defer db.mu.RUnlock()

	var active []VirtualPatch
	for _, patch := range db.patches {
		if patch.Enabled {
			active = append(active, *patch)
		}
	}
	return active
}

// GetAllPatches returns copies of all patches (both enabled and disabled).
func (db *Database) GetAllPatches() []VirtualPatch {
	db.mu.RLock()
	defer db.mu.RUnlock()

	all := make([]VirtualPatch, 0, len(db.patches))
	for _, patch := range db.patches {
		all = append(all, *patch)
	}
	return all
}

// GetPatchesForProduct returns patches affecting a product.
func (db *Database) GetPatchesForProduct(cpe string) []*VirtualPatch {
	db.mu.RLock()
	defer db.mu.RUnlock()

	var patches []*VirtualPatch
	cveIDs := db.byProduct[cpe]
	for _, cveID := range cveIDs {
		if entry, ok := db.entries[cveID]; ok {
			for _, patch := range entry.Patches {
				if patch.Enabled {
					patches = append(patches, &patch)
				}
			}
		}
	}
	return patches
}

// Stats returns database statistics.
func (db *Database) Stats() DatabaseStats {
	db.mu.RLock()
	defer db.mu.RUnlock()

	stats := DatabaseStats{
		TotalCVEs:     len(db.entries),
		TotalPatches:  len(db.patches),
		ActivePatches: 0,
		BySeverity:    make(map[string]int),
	}

	for _, entry := range db.entries {
		stats.BySeverity[entry.Severity]++
	}

	for _, patch := range db.patches {
		if patch.Enabled {
			stats.ActivePatches++
		}
	}

	return stats
}

// DatabaseStats represents database statistics.
type DatabaseStats struct {
	TotalCVEs     int            `json:"total_cves"`
	TotalPatches  int            `json:"total_patches"`
	ActivePatches int            `json:"active_patches"`
	BySeverity    map[string]int `json:"by_severity"`
}

// MatchResult represents a patch match.
type MatchResult struct {
	CVEID       string
	PatchID     string
	PatchName   string
	Severity    string
	Score       int
	Description string
	MatchedAt   time.Time
}
