package virtualpatch

import (
	"testing"
)

// Regression (hunt round 13/25): AddCVE unconditionally replaced stored
// patches with freshly-ingested copies (Enabled=false, pending_review), and
// runUpdate re-ingests the entire rolling NVD window on every cycle — so an
// operator's reviewed-and-applied virtual patch was silently disabled by the
// next feed refresh. The enable/review decision must survive re-ingestion.

func refreshWindowEntry() *CVEEntry {
	return &CVEEntry{
		CVEID:       "CVE-2025-9999",
		Description: "Remote code execution via unsafe deserialization in the request path",
		CVSSScore:   9.8,
		Severity:    "CRITICAL",
		CWEs:        []string{"CWE-502"},
		Patches: []VirtualPatch{{
			ID:            "VP-CVE20259999",
			CVEID:         "CVE-2025-9999",
			Name:          "Auto-generated patch for CVE-2025-9999",
			Patterns:      []PatchPattern{{Type: "body", Pattern: "rO0", MatchType: "contains"}},
			Action:        "block",
			Score:         49,
			Severity:      "CRITICAL",
			MatchLogic:    "or",
			Enabled:       false,
			AutoGenerated: true,
			ReviewStatus:  "pending_review",
			Provenance:    "nvd:auto-generated",
		}},
		AutoGenerated: true,
		Active:        true,
	}
}

func TestFeedRefreshPreservesAppliedPatchState(t *testing.T) {
	// AutoUpdate unset: no background goroutine; the refresh is simulated
	// by re-calling AddCVE exactly as runUpdate does.
	l := NewLayer(&Config{Enabled: true})

	// First ingestion: the feed delivers the CVE.
	l.database.AddCVE(refreshWindowEntry())

	// The operator reviews and applies the patch.
	if !l.EnablePatchBy("VP-CVE20259999", "alice") {
		t.Fatalf("EnablePatchBy failed")
	}
	if got := l.database.GetPatch("VP-CVE20259999"); got == nil || !got.Enabled || got.ReviewStatus != "applied" {
		t.Fatalf("precondition: patch should be enabled+applied after review, got %+v", got)
	}

	// The rolling window re-delivers the SAME CVE on the next refresh —
	// exactly what runUpdate does on every cycle.
	l.database.AddCVE(refreshWindowEntry())

	got := l.database.GetPatch("VP-CVE20259999")
	if got == nil {
		t.Fatalf("patch disappeared after refresh")
	}
	if !got.Enabled {
		t.Fatalf("FAIL: the feed refresh silently disabled an operator-applied virtual patch (Enabled=false, ReviewStatus=%q) — the enable decision must survive re-ingestion", got.ReviewStatus)
	}
	if got.ReviewStatus != "applied" || got.AppliedBy != "alice" {
		t.Fatalf("FAIL: the feed refresh wiped the review metadata (ReviewStatus=%q, AppliedBy=%q)", got.ReviewStatus, got.AppliedBy)
	}
}

// An operator-disabled patch must stay disabled across refreshes too.
func TestFeedRefreshPreservesDisabledPatchState(t *testing.T) {
	l := NewLayer(&Config{Enabled: true})
	l.database.AddCVE(refreshWindowEntry())

	if !l.DisablePatchBy("VP-CVE20259999", "bob") {
		t.Fatalf("DisablePatchBy failed")
	}

	l.database.AddCVE(refreshWindowEntry())

	got := l.database.GetPatch("VP-CVE20259999")
	if got == nil || got.Enabled {
		t.Fatalf("FAIL: the feed refresh re-enabled an operator-disabled virtual patch (%+v)", got)
	}
	if got.ReviewStatus != "disabled" {
		t.Fatalf("FAIL: review metadata wiped by refresh (ReviewStatus=%q)", got.ReviewStatus)
	}
}
