package lfi

// linuxSensitivePaths contains paths commonly targeted in LFI attacks on Linux systems.
var linuxSensitivePaths = []string{
	"/etc/passwd",
	"/etc/shadow",
	"/etc/group",
	"/etc/hosts",
	"/etc/hostname",
	"/etc/resolv.conf",
	"/etc/issue",
	"/etc/motd",
	"/etc/crontab",
	"/etc/ssh/sshd_config",
	"/etc/ssh/ssh_config",
	"/etc/apache2/apache2.conf",
	"/etc/nginx/nginx.conf",
	"/etc/mysql/my.cnf",
	"/etc/php/php.ini",
	"/etc/fstab",
	"/etc/master.passwd",
	"/etc/security/passwd",
	"/proc/self/environ",
	"/proc/self/cmdline",
	"/proc/self/fd/0",
	"/proc/self/status",
	"/proc/self/mounts",
	"/proc/version",
	"/proc/cpuinfo",
	"/proc/meminfo",
	"/proc/net/tcp",
	"/var/log/auth.log",
	"/var/log/syslog",
	"/var/log/apache2/access.log",
	"/var/log/apache2/error.log",
	"/var/log/nginx/access.log",
	"/var/log/nginx/error.log",
}

// windowsSensitivePaths contains paths commonly targeted in LFI attacks on Windows systems.
var windowsSensitivePaths = []string{
	`C:\Windows\system32\config\sam`,
	`C:\Windows\system32\config\system`,
	`C:\Windows\system32\config\software`,
	`C:\Windows\system32\drivers\etc\hosts`,
	`C:\Windows\win.ini`,
	`C:\Windows\system.ini`,
	`C:\Windows\debug\NetSetup.log`,
	`C:\Windows\repair\sam`,
	`C:\Windows\repair\system`,
	`C:\boot.ini`,
	`C:\inetpub\wwwroot\web.config`,
	`C:\inetpub\logs\LogFiles`,
	`C:\Windows\Panther\Unattend.xml`,
	`C:\Windows\Panther\unattended.xml`,
	`C:\Windows\system32\inetsrv\config\applicationHost.config`,
	`C:\xampp\apache\conf\httpd.conf`,
	`C:\xampp\php\php.ini`,
	`C:\ProgramData\MySQL\MySQL Server 5.7\my.ini`,
	`C:\Users\Administrator\NTUser.dat`,
	`C:\Windows\System32\config\RegBack\SAM`,
}

// macosSensitivePaths contains paths commonly targeted in LFI attacks on macOS systems.
var macosSensitivePaths = []string{
	"/etc/master.passwd",
	"/etc/resolv.conf",
	"/etc/hosts",
	"/etc/apache2/httpd.conf",
	"/etc/php.ini",
	"/private/etc/passwd",
	"/private/etc/master.passwd",
	"/private/etc/hosts",
	"/private/var/log/system.log",
	"/private/var/log/asl",
	"/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist",
	"/Users/Shared",
	"/var/log/system.log",
	"/var/log/install.log",
	"/Library/Logs/DiagnosticReports",
}
