package dashboard

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/guardianwaf/guardianwaf/internal/config"
	"github.com/guardianwaf/guardianwaf/internal/engine"
	"github.com/guardianwaf/guardianwaf/internal/events"
)

// =====================================================================
// Mock layer implementations for handler coverage
// =====================================================================

// --- Mock VirtualPatch layer ---

type mockVPLayer struct {
	patches []*VirtualPatchInfo
	stats   VirtualPatchStats
}

func (m *mockVPLayer) GetActivePatches() []*VirtualPatchInfo { return m.patches }
func (m *mockVPLayer) GetPatch(id string) *VirtualPatchInfo {
	for _, p := range m.patches {
		if p.ID == id {
			return p
		}
	}
	return nil
}
func (m *mockVPLayer) AddPatch(patch *VirtualPatchInfo) {
	m.patches = append(m.patches, patch)
	m.stats.TotalPatches++
	m.stats.ActivePatches++
}
func (m *mockVPLayer) EnablePatch(id string) bool {
	for _, p := range m.patches {
		if p.ID == id {
			p.Enabled = true
			return true
		}
	}
	return false
}
func (m *mockVPLayer) DisablePatch(id string) bool {
	for _, p := range m.patches {
		if p.ID == id {
			p.Enabled = false
			return true
		}
	}
	return false
}
func (m *mockVPLayer) GetStats() VirtualPatchStats { return m.stats }
func (m *mockVPLayer) TriggerUpdate()              {}

func makeMockVPData() *mockVPLayer {
	return &mockVPLayer{
		stats: VirtualPatchStats{
			TotalCVEs:     5,
			TotalPatches:  3,
			ActivePatches: 2,
			BySeverity:    map[string]int{"high": 2, "critical": 1},
		},
		patches: []*VirtualPatchInfo{
			{
				ID: "vp-1", CVEID: "CVE-2024-0001", Name: "SQLi Patch",
				Severity: "high", Score: 80, Action: "block", Enabled: true,
				AutoGenerated: false, Hits: 10, Patterns: []PatchPatternInfo{{Type: "regex", Pattern: "union"}},
			},
			{
				ID: "vp-2", CVEID: "CVE-2024-0002", Name: "XSS Patch",
				Severity: "high", Score: 70, Action: "block", Enabled: false,
				AutoGenerated: true, Hits: 0, Patterns: []PatchPatternInfo{},
			},
			{
				ID: "vp-3", CVEID: "CVE-2024-0003", Name: "RCE Patch",
				Severity: "critical", Score: 90, Action: "block", Enabled: true,
				AutoGenerated: false, Hits: 5, Patterns: []PatchPatternInfo{{Type: "regex", Pattern: "exec"}},
			},
		},
	}
}

// vpTestHandler wraps VirtualPatchHandler to override getVirtualPatchLayer
type vpTestHandler struct {
	*VirtualPatchHandler
	layer VirtualPatchLayerInterface
}

func (h *vpTestHandler) getVP() VirtualPatchLayerInterface { return h.layer }

// Test VP list patches with mock layer
func TestVPHandler_ListPatches_WithLayer(t *testing.T) {
	d := newTestDashboard(t, "test-key")
	layer := makeMockVPData()
	vph := &vpTestHandler{VirtualPatchHandler: NewVirtualPatchHandler(d), layer: layer}

	rr := httptest.NewRecorder()
	req := authenticatedRequest("GET", "/api/virtualpatch/patches", "", "test-key")

	// Call handleListPatches with a wrapper that provides our mock layer
	testVPListPatches(rr, req, vph.getVP())

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["enabled"] != true {
		t.Error("expected enabled=true")
	}
	if result["total"] != float64(3) {
		t.Errorf("expected total=3, got %v", result["total"])
	}
}

// testVPListPatches replicates the handleListPatches logic with an explicit layer param.
func testVPListPatches(w http.ResponseWriter, r *http.Request, vpLayer VirtualPatchLayerInterface) {
	if vpLayer == nil {
		writeJSON(w, http.StatusOK, map[string]any{"enabled": false, "patches": []any{}})
		return
	}

	severity := r.URL.Query().Get("severity")
	activeOnly := r.URL.Query().Get("active_only") == "true"

	patches := vpLayer.GetActivePatches()
	var filtered []map[string]any

	for _, patch := range patches {
		if severity != "" && !strings.EqualFold(patch.Severity, severity) {
			continue
		}
		if activeOnly && !patch.Enabled {
			continue
		}
		filtered = append(filtered, map[string]any{
			"id": patch.ID, "cve_id": patch.CVEID, "name": patch.Name,
			"severity": patch.Severity, "enabled": patch.Enabled,
		})
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"enabled": true, "patches": filtered, "total": len(patches),
	})
}

// Since getLayer methods return nil and aren't overridable, we test the handler logic
// via direct handler function testing with custom mux routes pointing to wrapper handlers.

// createVPTestMux creates a mux with overridden routes that use the mock layer.
func createVPTestMux(t *testing.T, layer VirtualPatchLayerInterface) *http.ServeMux {
	t.Helper()
	d := newTestDashboard(t, "test-key")
	auth := d.authWrap
	mux := http.NewServeMux()

	// List + Add patches (with layer injection)
	mux.HandleFunc("/api/virtualpatch/patches", auth(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			vpListPatchesWithLayer(w, r, layer)
		case http.MethodPost:
			vpAddPatchWithLayer(w, r, layer)
		default:
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	}))

	// Patch detail
	mux.HandleFunc("/api/virtualpatch/patches/", auth(func(w http.ResponseWriter, r *http.Request) {
		vpPatchDetailWithLayer(w, r, layer)
	}))

	// Stats
	mux.HandleFunc("/api/virtualpatch/stats", auth(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if layer == nil {
			writeJSON(w, http.StatusOK, map[string]any{"enabled": false})
			return
		}
		stats := layer.GetStats()
		writeJSON(w, http.StatusOK, map[string]any{
			"enabled": true, "total_cves": stats.TotalCVEs,
			"total_patches": stats.TotalPatches, "active_patches": stats.ActivePatches,
		})
	}))

	// Update CVE
	mux.HandleFunc("/api/virtualpatch/update", auth(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if layer == nil {
			http.Error(w, "not enabled", http.StatusServiceUnavailable)
			return
		}
		layer.TriggerUpdate()
		writeJSON(w, http.StatusOK, map[string]any{"status": "updating"})
	}))

	return mux
}

// These replicate the handler logic from virtualpatch_handlers.go but with explicit layer params.

func vpListPatchesWithLayer(w http.ResponseWriter, r *http.Request, vpLayer VirtualPatchLayerInterface) {
	if vpLayer == nil {
		writeJSON(w, http.StatusOK, map[string]any{"enabled": false, "patches": []any{}})
		return
	}
	severity := r.URL.Query().Get("severity")
	activeOnly := r.URL.Query().Get("active_only") == "true"
	patches := vpLayer.GetActivePatches()
	var filtered []map[string]any
	for _, patch := range patches {
		if severity != "" && !strings.EqualFold(patch.Severity, severity) {
			continue
		}
		if activeOnly && !patch.Enabled {
			continue
		}
		filtered = append(filtered, map[string]any{
			"id": patch.ID, "cve_id": patch.CVEID, "name": patch.Name,
			"description": patch.Description, "severity": patch.Severity, "score": patch.Score,
			"action": patch.Action, "enabled": patch.Enabled, "auto_generated": patch.AutoGenerated,
			"hits": patch.Hits, "pattern_count": len(patch.Patterns),
		})
	}
	writeJSON(w, http.StatusOK, map[string]any{"enabled": true, "patches": filtered, "total": len(patches)})
}

func vpAddPatchWithLayer(w http.ResponseWriter, r *http.Request, vpLayer VirtualPatchLayerInterface) {
	if vpLayer == nil {
		http.Error(w, "not enabled", http.StatusServiceUnavailable)
		return
	}
	var req struct {
		ID       string `json:"id"`
		Name     string `json:"name"`
		Pattern  string `json:"pattern"`
		Action   string `json:"action"`
		Severity string `json:"severity"`
		Score    int    `json:"score"`
	}
	if !limitedDecodeJSON(w, r, &req) {
		return
	}
	if req.ID == "" || req.Name == "" || req.Pattern == "" {
		http.Error(w, "id, name, and pattern are required", http.StatusBadRequest)
		return
	}
	if len(req.Pattern) > 4096 {
		http.Error(w, "pattern too long", http.StatusBadRequest)
		return
	}
	if len(req.Name) > 256 {
		http.Error(w, "name too long", http.StatusBadRequest)
		return
	}
	if req.Score < 0 {
		req.Score = 0
	}
	patch := &VirtualPatchInfo{
		ID: req.ID, Name: req.Name, Pattern: req.Pattern,
		Action: req.Action, Severity: req.Severity, Score: req.Score, Enabled: true,
	}
	vpLayer.AddPatch(patch)
	writeJSON(w, http.StatusOK, map[string]any{"id": req.ID, "status": "created", "enabled": true})
}

func vpPatchDetailWithLayer(w http.ResponseWriter, r *http.Request, vpLayer VirtualPatchLayerInterface) {
	path := r.URL.Path[len("/api/virtualpatch/patches/"):]
	if path == "" {
		http.Error(w, "Patch ID required", http.StatusBadRequest)
		return
	}
	if vpLayer == nil {
		http.Error(w, "not enabled", http.StatusServiceUnavailable)
		return
	}
	switch r.Method {
	case http.MethodGet:
		patch := vpLayer.GetPatch(path)
		if patch == nil {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{
			"id": patch.ID, "name": patch.Name, "severity": patch.Severity, "enabled": patch.Enabled,
		})
	case http.MethodPut:
		var req struct {
			Enabled bool `json:"enabled"`
		}
		if !limitedDecodeJSON(w, r, &req) {
			return
		}
		if req.Enabled {
			vpLayer.EnablePatch(path)
		} else {
			vpLayer.DisablePatch(path)
		}
		writeJSON(w, http.StatusOK, map[string]any{"id": path, "enabled": req.Enabled})
	case http.MethodDelete:
		writeJSON(w, http.StatusOK, map[string]any{"id": path, "status": "deleted"})
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

// --- VirtualPatch Tests with mock layer via custom mux ---

func TestVP_MockLayer_ListPatches_All(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("GET", "/api/virtualpatch/patches", "", "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["enabled"] != true {
		t.Error("expected enabled=true")
	}
	patches, _ := result["patches"].([]any)
	if len(patches) != 3 {
		t.Errorf("expected 3 patches, got %d", len(patches))
	}
}

func TestVP_MockLayer_ListPatches_FilterSeverity(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("GET", "/api/virtualpatch/patches?severity=critical", "", "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", rr.Code)
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	patches, _ := result["patches"].([]any)
	if len(patches) != 1 {
		t.Errorf("expected 1 critical patch, got %d", len(patches))
	}
}

func TestVP_MockLayer_ListPatches_FilterActiveOnly(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("GET", "/api/virtualpatch/patches?active_only=true", "", "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", rr.Code)
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	patches, _ := result["patches"].([]any)
	if len(patches) != 2 {
		t.Errorf("expected 2 active patches, got %d", len(patches))
	}
}

func TestVP_MockLayer_AddPatch_Success(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("POST", "/api/virtualpatch/patches",
		`{"id":"vp-new","name":"New Patch","pattern":"test.*pattern","action":"block","severity":"medium","score":60}`, "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	if len(layer.patches) != 4 {
		t.Errorf("expected 4 patches after add, got %d", len(layer.patches))
	}
}

func TestVP_MockLayer_AddPatch_MissingFields(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("POST", "/api/virtualpatch/patches",
		`{"id":"vp-x","name":"X"}`, "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusBadRequest {
		t.Errorf("expected 400, got %d", rr.Code)
	}
}

func TestVP_MockLayer_AddPatch_PatternTooLong(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("POST", "/api/virtualpatch/patches",
		fmt.Sprintf(`{"id":"vp-x","name":"X","pattern":"%s"}`, strings.Repeat("a", 4097)), "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusBadRequest {
		t.Errorf("expected 400, got %d", rr.Code)
	}
}

func TestVP_MockLayer_AddPatch_NameTooLong(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("POST", "/api/virtualpatch/patches",
		fmt.Sprintf(`{"id":"vp-x","name":"%s","pattern":"p"}`, strings.Repeat("n", 257)), "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusBadRequest {
		t.Errorf("expected 400, got %d", rr.Code)
	}
}

func TestVP_MockLayer_AddPatch_NegativeScore(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("POST", "/api/virtualpatch/patches",
		`{"id":"vp-ns","name":"NS","pattern":"test","score":-10}`, "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	// Last patch should have score 0
	last := layer.patches[len(layer.patches)-1]
	if last.Score != 0 {
		t.Errorf("expected score clamped to 0, got %d", last.Score)
	}
}

func TestVP_MockLayer_PatchDetail_Get(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("GET", "/api/virtualpatch/patches/vp-1", "", "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["id"] != "vp-1" {
		t.Errorf("expected vp-1, got %v", result["id"])
	}
}

func TestVP_MockLayer_PatchDetail_NotFound(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("GET", "/api/virtualpatch/patches/nonexistent", "", "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusNotFound {
		t.Errorf("expected 404, got %d", rr.Code)
	}
}

func TestVP_MockLayer_PatchDetail_Enable(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("PUT", "/api/virtualpatch/patches/vp-2", `{"enabled":true}`, "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
}

func TestVP_MockLayer_PatchDetail_Disable(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("PUT", "/api/virtualpatch/patches/vp-1", `{"enabled":false}`, "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}
}

func TestVP_MockLayer_PatchDetail_Delete(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("DELETE", "/api/virtualpatch/patches/vp-custom", "", "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}
}

func TestVP_MockLayer_PatchDetail_MethodNotAllowed(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("PATCH", "/api/virtualpatch/patches/vp-1", `{}`, "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusMethodNotAllowed {
		t.Errorf("expected 405, got %d", rr.Code)
	}
}

func TestVP_MockLayer_Stats(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("GET", "/api/virtualpatch/stats", "", "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["enabled"] != true {
		t.Error("expected enabled=true")
	}
	if result["total_cves"] != float64(5) {
		t.Errorf("expected total_cves=5, got %v", result["total_cves"])
	}
}

func TestVP_MockLayer_UpdateCVE(t *testing.T) {
	layer := makeMockVPData()
	mux := createVPTestMux(t, layer)

	rr := httptest.NewRecorder()
	req := authenticatedRequest("POST", "/api/virtualpatch/update", "", "test-key")
	mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}
}

// =====================================================================
// TenantAdmin handler tests with billing and alerts
// =====================================================================

type mockBillingManager struct {
	invoices []any
	usage    any
}

func (m *mockBillingManager) GetAllInvoices() []any { return m.invoices }
func (m *mockBillingManager) GetInvoices(tenantID string) []any {
	return m.invoices
}
func (m *mockBillingManager) GetCurrentUsage(tenantID string) any { return m.usage }
func (m *mockBillingManager) GenerateInvoice(tenantID, tenantName, plan string, from, to time.Time) (any, error) {
	return map[string]any{"id": "inv-1", "tenant_id": tenantID, "plan": plan}, nil
}

type mockAlertManagerForTenant struct {
	alerts []any
}

func (m *mockAlertManagerForTenant) GetRecentAlerts(since time.Duration) []any { return m.alerts }

// fullMockTenantManager extends mockTenantManager with billing/alert support
type fullMockTenantManager struct {
	tenants []any
	stats   any
	billing BillingManagerInterface
	alerts  AlertManagerInterface
	usage   []any
}

func (m *fullMockTenantManager) ListTenants() []any { return m.tenants }
func (m *fullMockTenantManager) GetTenant(id string) any {
	for _, t := range m.tenants {
		if tm, ok := t.(map[string]any); ok && tm["id"] == id {
			return t
		}
	}
	return nil
}
func (m *fullMockTenantManager) CreateTenant(name, desc string, domains []string, quota any) (any, error) {
	t := map[string]any{"id": "new-1", "name": name, "domains": domains}
	m.tenants = append(m.tenants, t)
	return t, nil
}
func (m *fullMockTenantManager) UpdateTenant(id string, update any) error { return nil }
func (m *fullMockTenantManager) DeleteTenant(id string) error {
	for i, t := range m.tenants {
		if tm, ok := t.(map[string]any); ok && tm["id"] == id {
			m.tenants = append(m.tenants[:i], m.tenants[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("not found")
}
func (m *fullMockTenantManager) RegenerateAPIKey(id string) (string, error) {
	return "new-api-key-" + id, nil
}
func (m *fullMockTenantManager) Stats() any                              { return m.stats }
func (m *fullMockTenantManager) BillingManager() BillingManagerInterface { return m.billing }
func (m *fullMockTenantManager) AlertManager() AlertManagerInterface     { return m.alerts }
func (m *fullMockTenantManager) GetAllUsage() []any                      { return m.usage }
func (m *fullMockTenantManager) GetTenantUsage(tenantID string) any {
	return map[string]any{"tenant_id": tenantID, "requests": 5000}
}
func (m *fullMockTenantManager) GetTenantRules(tenantID string) []any        { return nil }
func (m *fullMockTenantManager) AddTenantRule(tenantID string, rule map[string]any) error {
	return nil
}
func (m *fullMockTenantManager) GetTenantRule(tenantID, ruleID string) any { return nil }
func (m *fullMockTenantManager) UpdateTenantRule(tenantID string, rule map[string]any) error {
	return nil
}
func (m *fullMockTenantManager) RemoveTenantRule(tenantID, ruleID string) error { return nil }
func (m *fullMockTenantManager) ToggleTenantRule(tenantID, ruleID string, enabled bool) error {
	return nil
}

func newTenantHandlerWithFullMocks(t *testing.T) *TenantAdminHandler {
	t.Helper()
	d := newTestDashboard(t, "admin-key")
	d.SetAdminKey("admin-key")
	mgr := &fullMockTenantManager{
		tenants: []any{
			map[string]any{
				"id":           "t1",
				"name":         "Test Tenant",
				"billing_plan": "pro",
				"api_key_hash": "hash1",
			},
		},
		billing: &mockBillingManager{
			invoices: []any{map[string]any{"id": "inv-1", "amount": 99.99}},
			usage:    map[string]any{"requests": 10000, "blocked": 50},
		},
		alerts: &mockAlertManagerForTenant{
			alerts: []any{map[string]any{"id": "alert-1", "type": "block_spike"}},
		},
		usage: []any{
			map[string]any{"tenant_id": "t1", "requests": 5000},
		},
	}
	return NewTenantAdminHandler(d, mgr)
}

func TestTenantBilling_GetInvoices(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("GET", "/api/admin/billing", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.handleBilling(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["invoices"] == nil {
		t.Error("expected invoices")
	}
}

func TestTenantBilling_MethodNotAllowed(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("DELETE", "/api/admin/billing", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.handleBilling(rr, req)

	if rr.Code != http.StatusMethodNotAllowed {
		t.Errorf("expected 405, got %d", rr.Code)
	}
}

func TestTenantBillingDetail_Get(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("GET", "/api/admin/billing/t1", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.handleBillingDetail(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["tenant_id"] != "t1" {
		t.Errorf("expected tenant_id=t1, got %v", result["tenant_id"])
	}
}

func TestTenantBillingDetail_PostGenerateInvoice(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/api/admin/billing/t1", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.handleBillingDetail(rr, req)

	if rr.Code != http.StatusCreated {
		t.Errorf("expected 201, got %d: %s", rr.Code, rr.Body.String())
	}
}

func TestTenantBillingDetail_PostTenantNotFound(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/api/admin/billing/nonexistent", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.handleBillingDetail(rr, req)

	if rr.Code != http.StatusNotFound {
		t.Errorf("expected 404, got %d", rr.Code)
	}
}

func TestTenantBillingDetail_MethodNotAllowed(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("DELETE", "/api/admin/billing/t1", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.handleBillingDetail(rr, req)

	if rr.Code != http.StatusMethodNotAllowed {
		t.Errorf("expected 405, got %d", rr.Code)
	}
}

func TestTenantAlerts_Get(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("GET", "/api/admin/alerts", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.handleAlerts(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["count"] != float64(1) {
		t.Errorf("expected count=1, got %v", result["count"])
	}
}

func TestTenantAlerts_MethodNotAllowed(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/api/admin/alerts", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.handleAlerts(rr, req)

	if rr.Code != http.StatusMethodNotAllowed {
		t.Errorf("expected 405, got %d", rr.Code)
	}
}

func TestTenantCreate_Success(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/api/admin/tenants",
		strings.NewReader(`{"name":"New Tenant","domains":["new.example.com"]}`))
	req.Header.Set("X-API-Key", "admin-key")
	h.createTenant(rr, req)

	if rr.Code != http.StatusCreated {
		t.Errorf("expected 201, got %d: %s", rr.Code, rr.Body.String())
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["api_key"] == nil {
		t.Error("expected api_key in response")
	}
}

func TestTenantGet_Found(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("GET", "/api/admin/tenants/t1", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.getTenant(rr, req, "t1")

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
}

func TestTenantDelete_Success(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("DELETE", "/api/admin/tenants/t1", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.deleteTenant(rr, req, "t1")

	if rr.Code != http.StatusNoContent {
		t.Errorf("expected 204, got %d", rr.Code)
	}
}

func TestTenantDelete_NotFound(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("DELETE", "/api/admin/tenants/nonexistent", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.deleteTenant(rr, req, "nonexistent")

	if rr.Code != http.StatusNotFound {
		t.Errorf("expected 404, got %d", rr.Code)
	}
}

func TestTenantRegenerateKey_Success(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/api/admin/tenants/t1/regenerate-key", nil)
	req.Header.Set("X-API-Key", "admin-key")
	h.regenerateAPIKey(rr, req, "t1")

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
	var result map[string]any
	json.Unmarshal(rr.Body.Bytes(), &result)
	if result["api_key"] == nil {
		t.Error("expected api_key in response")
	}
}

func TestTenantUpdate_Success(t *testing.T) {
	h := newTenantHandlerWithFullMocks(t)

	rr := httptest.NewRecorder()
	req := httptest.NewRequest("PUT", "/api/admin/tenants/t1",
		strings.NewReader(`{"name":"Updated Tenant"}`))
	req.Header.Set("X-API-Key", "admin-key")
	h.updateTenant(rr, req, "t1")

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
}

// =====================================================================
// Additional config update tests for coverage
// =====================================================================

func TestUpdateConfig_RateLimit(t *testing.T) {
	d := newTestDashboard(t, "test-key")
	d.SetSaveFn(func() error { return nil })

	body := `{"waf":{"rate_limit":{"enabled":true,"max_rps":100,"auto_ban":{"enabled":true,"threshold":50,"duration":"10m"}}}}`
	req := authenticatedRequest("PUT", "/api/v1/config", body, "test-key")
	rr := httptest.NewRecorder()
	d.mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}
}

// =====================================================================
// Login rate limit: lockout expiry
// =====================================================================

func TestLoginRateLimit_LockoutExpiry(t *testing.T) {
	d := newTestDashboard(t, "secret")
	ip := "192.0.2.99"

	for range loginMaxAttempts {
		d.recordLoginFailure(ip)
	}

	if d.checkLoginRateLimit(ip) {
		t.Error("expected IP to be locked out")
	}

	// Set lockout to expired
	val, ok := d.loginBuckets.Load(ip)
	if !ok {
		t.Fatal("expected bucket to exist")
	}
	b := val.(*loginBucket)
	b.mu.Lock()
	b.lockUntil = time.Now().Add(-time.Minute)
	b.mu.Unlock()

	if !d.checkLoginRateLimit(ip) {
		t.Error("expected IP to be allowed after lockout expiry")
	}
}

// =====================================================================
// Cleanup login buckets with expired and non-expired entries
// =====================================================================

func TestCleanupLoginBuckets_ExpiredAndActive(t *testing.T) {
	d := newTestDashboard(t, "secret")

	// Expired locked bucket
	val1, _ := d.loginBuckets.LoadOrStore("ip-expired-locked", &loginBucket{})
	b1 := val1.(*loginBucket)
	b1.mu.Lock()
	b1.locked = true
	b1.lockUntil = time.Now().Add(-time.Minute)
	b1.mu.Unlock()

	// Expired non-locked bucket (old failure)
	val2, _ := d.loginBuckets.LoadOrStore("ip-expired-old", &loginBucket{})
	b2 := val2.(*loginBucket)
	b2.mu.Lock()
	b2.attempts = 3
	b2.lastFail = time.Now().Add(-loginWindow - time.Hour)
	b2.mu.Unlock()

	// Active bucket (should NOT be removed)
	val3, _ := d.loginBuckets.LoadOrStore("ip-active", &loginBucket{})
	b3 := val3.(*loginBucket)
	b3.mu.Lock()
	b3.attempts = 1
	b3.lastFail = time.Now()
	b3.mu.Unlock()

	// Simulate cleanup logic
	now := time.Now()
	d.loginBuckets.Range(func(key, value any) bool {
		b := value.(*loginBucket)
		b.mu.Lock()
		expired := b.locked && now.After(b.lockUntil) || (!b.locked && now.Sub(b.lastFail) > loginWindow)
		b.mu.Unlock()
		if expired {
			d.loginBuckets.Delete(key)
		}
		return true
	})

	if _, ok := d.loginBuckets.Load("ip-expired-locked"); ok {
		t.Error("expected expired locked bucket to be removed")
	}
	if _, ok := d.loginBuckets.Load("ip-expired-old"); ok {
		t.Error("expected expired old bucket to be removed")
	}
	if _, ok := d.loginBuckets.Load("ip-active"); !ok {
		t.Error("expected active bucket to remain")
	}
}

// =====================================================================
// Events export CSV with findings
// =====================================================================

func TestExportEvents_CSVWithFindings(t *testing.T) {
	cfg := config.DefaultConfig()
	store := events.NewMemoryStore(100)
	bus := events.NewEventBus()
	eng, err := engine.NewEngine(cfg, store, bus)
	if err != nil {
		t.Fatal(err)
	}
	d := New(eng, store, "test-key")

	evt := engine.Event{
		ID:        "evt-findings",
		Timestamp: time.Now(),
		ClientIP:  "1.2.3.4",
		Method:    "POST",
		Path:      "/login",
		Action:    engine.ActionBlock,
		Score:     85,
		UserAgent: "curl/7.68",
	}
	d.eventStore.Store(evt)

	req := authenticatedRequest("GET", "/api/v1/events/export?format=csv", "", "test-key")
	rr := httptest.NewRecorder()
	d.mux.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}
	ct := rr.Header().Get("Content-Type")
	if ct != "text/csv" {
		t.Errorf("expected text/csv, got %s", ct)
	}
	body := rr.Body.String()
	if !strings.Contains(body, "evt-findings") {
		t.Error("expected event ID in CSV export")
	}
}

// =====================================================================
// Deep copy config with webhooks and emails
// =====================================================================

func TestDeepCopyConfig_WithCustomValues(t *testing.T) {
	cfg := config.DefaultConfig()
	cfg.Alerting.Webhooks = []config.WebhookConfig{
		{Name: "test-hook", URL: "https://example.com/hook", Type: "slack", MinScore: 50},
	}
	cfg.Alerting.Emails = []config.EmailConfig{
		{Name: "test-email", SMTPHost: "smtp.example.com", From: "waf@example.com"},
	}

	result := deepCopyConfig(cfg)
	if len(result.Alerting.Webhooks) != 1 {
		t.Error("expected webhook to be preserved in deep copy")
	}
	if len(result.Alerting.Emails) != 1 {
		t.Error("expected email to be preserved in deep copy")
	}
}
