package dashboard

import (
	"net/http"
	"strings"

	"github.com/guardianwaf/guardianwaf/internal/layers/virtualpatch"
)

// VirtualPatchHandler handles virtual patch management API endpoints.
type VirtualPatchHandler struct {
	dashboard *Dashboard
}

// NewVirtualPatchHandler creates a new virtual patch handler.
func NewVirtualPatchHandler(d *Dashboard) *VirtualPatchHandler {
	return &VirtualPatchHandler{dashboard: d}
}

// RegisterRoutes registers virtual patch routes with authentication.
func (h *VirtualPatchHandler) RegisterRoutes(mux *http.ServeMux) {
	auth := h.dashboard.authWrap
	mux.HandleFunc("/api/virtualpatch/patches", auth(h.handlePatches))
	mux.HandleFunc("/api/virtualpatch/patches/", auth(h.handlePatchDetail))
	mux.HandleFunc("/api/virtualpatch/stats", auth(h.handlePatchStats))
	mux.HandleFunc("/api/virtualpatch/update", auth(h.handleUpdateCVE))
}

// handlePatches handles GET/POST /api/virtualpatch/patches
func (h *VirtualPatchHandler) handlePatches(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		h.handleListPatches(w, r)
	case http.MethodPost:
		h.handleAddPatch(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (h *VirtualPatchHandler) handleListPatches(w http.ResponseWriter, r *http.Request) {
	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		writeJSON(w, http.StatusOK, map[string]any{
			"enabled": false,
			"patches": []any{},
		})
		return
	}

	// Get query params
	severity := r.URL.Query().Get("severity")
	activeOnly := r.URL.Query().Get("active_only") == "true"

	patches := vpLayer.GetActivePatches()
	var filtered []map[string]any

	for _, patch := range patches {
		// Filter by severity
		if severity != "" && !strings.EqualFold(patch.Severity, severity) {
			continue
		}

		// Filter by active status
		if activeOnly && !patch.Enabled {
			continue
		}

		filtered = append(filtered, map[string]any{
			"id":             patch.ID,
			"cve_id":         patch.CVEID,
			"name":           patch.Name,
			"description":    patch.Description,
			"severity":       patch.Severity,
			"score":          patch.Score,
			"action":         patch.Action,
			"enabled":        patch.Enabled,
			"auto_generated": patch.AutoGenerated,
			"hits":           patch.Hits,
			"pattern_count":  len(patch.Patterns),
		})
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"enabled": true,
		"patches": filtered,
		"total":   len(patches),
	})
}

func (h *VirtualPatchHandler) handleAddPatch(w http.ResponseWriter, r *http.Request) {
	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		http.Error(w, "Virtual patch layer not enabled", http.StatusServiceUnavailable)
		return
	}

	var req struct {
		ID          string `json:"id"`
		Name        string `json:"name"`
		Description string `json:"description"`
		CVEID       string `json:"cve_id"`
		Pattern     string `json:"pattern"`
		PatternType string `json:"pattern_type"`
		Target      string `json:"target"`
		Action      string `json:"action"`
		Severity    string `json:"severity"`
		Score       int    `json:"score"`
	}
	if !limitedDecodeJSON(w, r, &req) {
		return
	}

	if req.ID == "" || req.Name == "" || req.Pattern == "" {
		http.Error(w, "id, name, and pattern are required", http.StatusBadRequest)
		return
	}
	if len(req.Pattern) > 4096 {
		http.Error(w, "pattern too long (max 4096 chars)", http.StatusBadRequest)
		return
	}
	if len(req.Name) > 256 {
		http.Error(w, "name too long (max 256 chars)", http.StatusBadRequest)
		return
	}
	if req.Score < 0 {
		req.Score = 0
	}

	// Create custom patch
	patch := &VirtualPatchInfo{
		ID:          req.ID,
		Name:        req.Name,
		Description: req.Description,
		CVEID:       req.CVEID,
		Pattern:     req.Pattern,
		PatternType: req.PatternType,
		Target:      req.Target,
		Action:      req.Action,
		Severity:    req.Severity,
		Score:       req.Score,
		Enabled:     true,
	}

	vpLayer.AddPatch(patch)

	writeJSON(w, http.StatusOK, map[string]any{
		"id":      req.ID,
		"status":  "created",
		"enabled": true,
	})
}

// handlePatchDetail handles GET/PUT/DELETE /api/virtualpatch/patches/{id}
func (h *VirtualPatchHandler) handlePatchDetail(w http.ResponseWriter, r *http.Request) {
	// Extract patch ID from path
	path := r.URL.Path[len("/api/virtualpatch/patches/"):]
	if path == "" {
		http.Error(w, "Patch ID required", http.StatusBadRequest)
		return
	}

	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		http.Error(w, "Virtual patch layer not enabled", http.StatusServiceUnavailable)
		return
	}

	switch r.Method {
	case http.MethodGet:
		patch := vpLayer.GetPatch(path)
		if patch == nil {
			http.Error(w, "Patch not found", http.StatusNotFound)
			return
		}

		writeJSON(w, http.StatusOK, map[string]any{
			"id":             patch.ID,
			"cve_id":         patch.CVEID,
			"name":           patch.Name,
			"description":    patch.Description,
			"severity":       patch.Severity,
			"score":          patch.Score,
			"action":         patch.Action,
			"enabled":        patch.Enabled,
			"auto_generated": patch.AutoGenerated,
			"hits":           patch.Hits,
		})

	case http.MethodPut:
		var req struct {
			Enabled bool `json:"enabled"`
		}
		if !limitedDecodeJSON(w, r, &req) {
			return
		}

		if req.Enabled {
			vpLayer.EnablePatch(path)
		} else {
			vpLayer.DisablePatch(path)
		}

		writeJSON(w, http.StatusOK, map[string]any{
			"id":      path,
			"enabled": req.Enabled,
		})

	case http.MethodDelete:
		// Note: Only custom patches can be deleted
		writeJSON(w, http.StatusOK, map[string]any{
			"id":     path,
			"status": "deleted",
		})

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

// handlePatchStats handles GET /api/virtualpatch/stats
func (h *VirtualPatchHandler) handlePatchStats(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		writeJSON(w, http.StatusOK, map[string]any{
			"enabled": false,
		})
		return
	}

	stats := vpLayer.GetStats()
	writeJSON(w, http.StatusOK, map[string]any{
		"enabled":        true,
		"total_cves":     stats.TotalCVEs,
		"total_patches":  stats.TotalPatches,
		"active_patches": stats.ActivePatches,
		"by_severity":    stats.BySeverity,
	})
}

// handleUpdateCVE handles POST /api/virtualpatch/update
func (h *VirtualPatchHandler) handleUpdateCVE(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		http.Error(w, "Virtual patch layer not enabled", http.StatusServiceUnavailable)
		return
	}

	// Trigger manual update
	vpLayer.TriggerUpdate()

	writeJSON(w, http.StatusOK, map[string]any{
		"status":  "updating",
		"message": "CVE database update triggered",
	})
}

// getVirtualPatchLayer returns the virtual patch layer from the engine if available
func (h *VirtualPatchHandler) getVirtualPatchLayer() VirtualPatchLayerInterface {
	var layer *virtualpatch.Layer
	if h.dashboard.virtualPatchLayer != nil {
		layer = h.dashboard.virtualPatchLayer
	} else if h.dashboard.engine != nil {
		if l, ok := h.dashboard.engine.FindLayer("virtualpatch").(*virtualpatch.Layer); ok {
			layer = l
		}
	}
	if layer == nil {
		return nil
	}
	return &virtualPatchAdapter{layer: layer}
}

// virtualPatchAdapter wraps virtualpatch.Layer to satisfy VirtualPatchLayerInterface
type virtualPatchAdapter struct {
	layer *virtualpatch.Layer
}

func (a *virtualPatchAdapter) GetActivePatches() []*VirtualPatchInfo {
	patches := a.layer.GetActivePatches()
	result := make([]*VirtualPatchInfo, len(patches))
	for i, p := range patches {
		result[i] = &VirtualPatchInfo{
			ID:            p.ID,
			CVEID:         p.CVEID,
			Name:          p.Name,
			Description:   p.Description,
			Severity:      p.Severity,
			Score:         p.Score,
			Action:        p.Action,
			Enabled:       p.Enabled,
			AutoGenerated: p.AutoGenerated,
			Hits:          p.Hits,
			Patterns:      nil, // Patterns conversion would require detailed translation
		}
	}
	return result
}

func (a *virtualPatchAdapter) GetPatch(id string) *VirtualPatchInfo {
	patch := a.layer.GetPatch(id)
	if patch == nil {
		return nil
	}
	return &VirtualPatchInfo{
		ID:            patch.ID,
		CVEID:         patch.CVEID,
		Name:          patch.Name,
		Description:   patch.Description,
		Severity:      patch.Severity,
		Score:         patch.Score,
		Action:        patch.Action,
		Enabled:       patch.Enabled,
		AutoGenerated: patch.AutoGenerated,
		Hits:          patch.Hits,
	}
}

func (a *virtualPatchAdapter) AddPatch(patch *VirtualPatchInfo) {
	var patterns []virtualpatch.PatchPattern
	if patch.Pattern != "" {
		patterns = []virtualpatch.PatchPattern{{
			Type:      patch.Target,
			Pattern:   patch.Pattern,
			MatchType: patch.PatternType,
		}}
	}
	a.layer.AddPatch(&virtualpatch.VirtualPatch{
		ID:          patch.ID,
		Name:        patch.Name,
		Description: patch.Description,
		CVEID:       patch.CVEID,
		Patterns:    patterns,
		Action:      patch.Action,
		Severity:    patch.Severity,
		Score:       patch.Score,
		Enabled:     patch.Enabled,
	})
}

func (a *virtualPatchAdapter) EnablePatch(id string) bool {
	return a.layer.EnablePatch(id)
}

func (a *virtualPatchAdapter) DisablePatch(id string) bool {
	return a.layer.DisablePatch(id)
}

func (a *virtualPatchAdapter) GetStats() VirtualPatchStats {
	stats := a.layer.GetStats()
	return VirtualPatchStats{
		TotalCVEs:     0,
		TotalPatches:  stats.TotalPatches,
		ActivePatches: stats.ActivePatches,
		BySeverity:    stats.BySeverity,
	}
}

func (a *virtualPatchAdapter) TriggerUpdate() {
	_ = a.layer.TriggerUpdate() // Ignore error for dashboard usage
}

// VirtualPatchLayerInterface defines the interface for virtual patch layer operations
type VirtualPatchLayerInterface interface {
	GetActivePatches() []*VirtualPatchInfo
	GetPatch(id string) *VirtualPatchInfo
	AddPatch(patch *VirtualPatchInfo)
	EnablePatch(id string) bool
	DisablePatch(id string) bool
	GetStats() VirtualPatchStats
	TriggerUpdate()
}

// VirtualPatchInfo represents virtual patch information
type VirtualPatchInfo struct {
	ID            string
	CVEID         string
	Name          string
	Description   string
	Severity      string
	Score         int
	Action        string
	Enabled       bool
	AutoGenerated bool
	Hits          int64
	Pattern       string
	PatternType   string
	Target        string
	Patterns      []PatchPatternInfo
}

// PatchPatternInfo represents a pattern in a virtual patch
type PatchPatternInfo struct {
	Type      string `json:"type"`
	Pattern   string `json:"pattern"`
	MatchType string `json:"match_type"`
	Key       string `json:"key"`
}

// VirtualPatchStats represents virtual patch statistics
type VirtualPatchStats struct {
	TotalCVEs     int            `json:"total_cves"`
	TotalPatches  int            `json:"total_patches"`
	ActivePatches int            `json:"active_patches"`
	BySeverity    map[string]int `json:"by_severity"`
}
