#!/bin/bash
# GuardianWAF Installation Script
# Usage: curl -sSL https://raw.githubusercontent.com/guardianwaf/guardianwaf/main/scripts/install.sh | bash
# Or: bash install.sh

set -e

REPO="guardianwaf/guardianwaf"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/guardianwaf"
DATA_DIR="/var/lib/guardianwaf"
SERVICE_DIR="/etc/systemd/system"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Detect OS
detect_os() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if command -v apt-get &> /dev/null; then
            echo "debian"
        elif command -v apk &> /dev/null; then
            echo "alpine"
        elif command -v yum &> /dev/null; then
            echo "rhel"
        else
            echo "linux"
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "darwin"
    else
        echo "unknown"
    fi
}

# Detect architecture
detect_arch() {
    local arch=$(uname -m)
    case $arch in
        x86_64) echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        armv7l) echo "armv7" ;;
        *)
            log_error "Unsupported architecture: $arch"
            exit 1
            ;;
    esac
}

# Generate secure password
generate_password() {
    head -c 32 /dev/urandom | base64 | tr -d '/+' | head -c 16
}

# Detect latest version
get_latest_version() {
    local version=$(curl -sSL "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name"' | sed -E 's/.*"v([^"]+)".*/\1/')
    echo "${version:-1.1.0}"
}

# Download and install binary
install_binary() {
    local version=$1
    local os=$2
    local arch=$3

    local ext=""
    if [[ "$os" == "windows" ]]; then
        ext=".zip"
    else
        ext=".tar.gz"
    fi

    local filename="guardianwaf_${version}_${os}_${arch}${ext}"
    local download_url="https://github.com/${REPO}/releases/download/v${version}/${filename}"

    log_info "Downloading GuardianWAF v${version} for ${os}/${arch}..."
    curl -fSL "$download_url" -o "/tmp/${filename}"

    log_info "Installing to ${INSTALL_DIR}..."
    mkdir -p "$INSTALL_DIR"

    if [[ "$ext" == ".zip" ]]; then
        unzip -o "/tmp/${filename}" -d "$INSTALL_DIR"
    else
        tar -xzf "/tmp/${filename}" -C "$INSTALL_DIR"
    fi

    chmod +x "${INSTALL_DIR}/guardianwaf"
    rm -f "/tmp/${filename}"

    log_info "GuardianWAF v${version} installed successfully!"
}

# Create production config
create_config() {
    log_info "Creating production configuration..."

    mkdir -p "$CONFIG_DIR"
    mkdir -p "$DATA_DIR"
    chmod 700 "$CONFIG_DIR"
    chmod 700 "$DATA_DIR"

    local config_file="${CONFIG_DIR}/guardianwaf.yaml"

    if [[ -f "$config_file" ]]; then
        log_warn "Config already exists at ${config_file}"
        return 0
    fi

    # Generate dashboard API key
    local dashboard_api_key=$(generate_password)

    cat > "$config_file" << EOF
# GuardianWAF Configuration
# Generated by install.sh on $(date)
mode: enforce
listen: ":8088"
# Explicitly allow the default localhost upstream generated by this installer.
allow_private_upstreams: true

tls:
  enabled: false
  listen: ":8443"

upstreams:
  - name: default
    targets:
      - url: "http://localhost:3000"
        weight: 1
    health_check:
      enabled: true
      interval: 10s
      timeout: 3s
      path: /healthz

routes:
  - path: /
    upstream: default
    strip_prefix: false

logging:
  level: info
  format: json
  output: stdout
  log_allowed: false
  log_blocked: true

waf:
  ip_acl:
    enabled: true
    whitelist: []
    blacklist: []
    auto_ban:
      enabled: true
      default_ttl: 1h
      max_ttl: 24h

  detection:
    enabled: true
    threshold:
      block: 50
      log: 25
    detectors:
      sqli:
        enabled: true
        multiplier: 1.0
      xss:
        enabled: true
        multiplier: 1.0
      lfi:
        enabled: true
        multiplier: 1.0
      cmdi:
        enabled: true
        multiplier: 1.0
      xxe:
        enabled: true
        multiplier: 1.0
      ssrf:
        enabled: true
        multiplier: 1.0

  challenge:
    enabled: true
    difficulty: 20
    cookie_ttl: 1h
    cookie_name: __gwaf_challenge

  bot_detection:
    enabled: true
    mode: enforce
    user_agent:
      enabled: true
      block_empty: true
      block_known_scanners: true

  rate_limit:
    enabled: true
    rules:
      - id: global
        scope: ip
        limit: 1000
        window: 1m
        burst: 50
        action: block

  sanitizer:
    enabled: true
    max_url_length: 8192
    max_header_size: 8192
    max_header_count: 100
    max_body_size: 10485760
    max_cookie_size: 4096
    block_null_bytes: true
    normalize_encoding: true
    strip_hop_by_hop: true
    allowed_methods: [GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS]

  cors:
    enabled: true
    allow_origins:
      - "*"
    allow_methods: [GET, POST, PUT, DELETE, OPTIONS]
    allow_headers:
      - "*"
    max_age_seconds: 86400

  ato_protection:
    enabled: true
    brute_force:
      enabled: true
      max_attempts_per_ip: 5
      window: 10m
      block_duration: 30m

  response:
    security_headers:
      enabled: true
      hsts:
        enabled: false
      x_content_type_options: true
      x_frame_options: SAMEORIGIN
      referrer_policy: strict-origin-when-cross-origin
    data_masking:
      enabled: true
      mask_credit_cards: true
      mask_ssn: true
      mask_api_keys: true
      strip_stack_traces: true
    error_pages:
      enabled: true
      mode: production

docker:
  enabled: false
  socket_path: /var/run/docker.sock
  label_prefix: gwaf
  poll_interval: 5s
  network: bridge

dashboard:
  enabled: true
  listen: ":9443"
  api_key: "$dashboard_api_key"
  admin_key: ""
  tls: false

alerting:
  enabled: false

mcp:
  enabled: false
  transport: stdio

events:
  storage: file
  max_events: 100000
  file_path: "${DATA_DIR}/events.jsonl"
EOF

    chmod 600 "$config_file"
    log_info "Config created at ${config_file}"
    log_warn "Dashboard API key generated: $dashboard_api_key"
    log_warn "IMPORTANT: Save this key! Set it via GWAF_DASHBOARD_API_KEY env or update dashboard.api_key."
}

# Install systemd service
install_service() {
    if [[ "$OS" != "linux" ]] && [[ $(detect_os) == "linux" ]]; then
        log_warn "Not running as root, skipping systemd service install"
        return 0
    fi

    if ! command -v systemctl &> /dev/null; then
        log_warn "systemd not found, skipping service installation"
        return 0
    fi

    log_step "Installing systemd service..."

    mkdir -p "$SERVICE_DIR"

    cat > "${SERVICE_DIR}/guardianwaf.service" << 'EOF'
[Unit]
Description=GuardianWAF - Zero-dependency Web Application Firewall
Documentation=https://github.com/guardianwaf/guardianwaf
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStart=/usr/local/bin/guardianwaf serve -c /etc/guardianwaf/guardianwaf.yaml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

Environment=GWAF_MODE=enforce
Environment=GWAF_LOGGING_LEVEL=info

[Install]
WantedBy=multi-user.target
EOF

    chmod 644 "${SERVICE_DIR}/guardianwaf.service"

    systemctl daemon-reload
    systemctl enable guardianwaf

    log_info "Systemd service installed and enabled!"
    log_info "Run: systemctl start guardianwaf"
}

# Install Docker image
install_docker() {
    log_info "Installing GuardianWAF via Docker..."

    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi

    docker pull "ghcr.io/${REPO}:latest"

    log_info "GuardianWAF Docker image installed!"
    log_info "Run with: docker run -d -p 8088:8088 -p 9443:9443 ghcr.io/${REPO}:latest"
}

# Print setup info
print_info() {
    echo
    echo "=========================================="
    echo "  GuardianWAF Installed Successfully!"
    echo "=========================================="
    echo
    echo "Installation Details:"
    echo "  Binary:   ${INSTALL_DIR}/guardianwaf"
    echo "  Config:   ${CONFIG_DIR}/guardianwaf.yaml"
    echo "  Data:     ${DATA_DIR}"
    echo
    echo "Quick Start:"
    echo "  # Start as service (recommended for Linux):"
    echo "  sudo systemctl start guardianwaf"
    echo "  sudo systemctl status guardianwaf"
    echo
    echo "  # Or run directly:"
    echo "  guardianwaf serve -c ${CONFIG_DIR}/guardianwaf.yaml"
    echo
    echo "  # Docker:"
    echo "  docker run -d -p 8088:8088 -p 9443:9443 ghcr.io/${REPO}:latest"
    echo
    echo "Access:"
    echo "  Dashboard: http://localhost:9443"
    echo "  Proxy:     http://localhost:8088"
    echo "  Health:    http://localhost:8088/healthz"
    echo "  Metrics:  http://localhost:8088/metrics"
    echo
    echo "Commands:"
    echo "  guardianwaf serve         # Start WAF"
    echo "  guardianwaf check         # Test request"
    echo "  guardianwaf validate      # Validate config"
    echo "  guardianwaf version       # Show version"
    echo
    echo "For updates: curl -sSL https://raw.githubusercontent.com/guardianwaf/guardianwaf/main/scripts/update.sh | bash"
    echo
}

# Main installation
main() {
    local install_type=${1:-"binary"}
    local version=${2:-$(get_latest_version)}
    local os=$(uname -s | tr '[:upper:]' '[:lower:]')
    local arch=$(detect_arch)

    # Windows detection
    if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
        os="windows"
    fi

    echo "=========================================="
    echo "  GuardianWAF Installation Script"
    echo "=========================================="
    echo
    log_info "Version: ${version}"
    log_info "OS/Arch: ${os}/${arch}"
    log_info "Install type: ${install_type}"
    echo

    case $install_type in
        docker)
            install_docker
            ;;
        binary|--binary)
            if ! command -v curl &> /dev/null; then
                log_error "curl is required for binary installation"
                exit 1
            fi
            install_binary "$version" "$os" "$arch"
            create_config

            if [[ "$os" == "linux" ]] && command -v systemctl &> /dev/null; then
                install_service
            fi
            ;;
        service|--service)
            install_binary "$version" "$os" "$arch"
            create_config
            install_service
            ;;
        *)
            if command -v curl &> /dev/null; then
                install_binary "$version" "$os" "$arch"
                create_config
                if [[ "$os" == "linux" ]] && command -v systemctl &> /dev/null; then
                    install_service
                fi
            else
                log_error "curl is required for binary installation"
                log_info "Try Docker installation: $0 docker"
                exit 1
            fi
            ;;
    esac

    print_info
}

main "$@"
