# GuardianWAF Installation Script for Windows
# Usage: powershell -ExecutionPolicy Bypass -File install.ps1
# Or: irm https://raw.githubusercontent.com/guardianwaf/guardianwaf/main/scripts/install.ps1 | iex

param(
    [string]$Version = "",
    [ValidateSet("binary", "docker")]
    [string]$InstallType = "binary",
    [string]$InstallDir = "$env:ProgramFiles\GuardianWAF",
    [string]$ConfigDir = "$env:ProgramData\GuardianWAF"
)

$ErrorActionPreference = "Stop"

$Repo = "guardianwaf/guardianwaf"
$BinaryName = "guardianwaf.exe"

function Write-Info { param($msg) Write-Host "[INFO] $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Err { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red }
function Write-Step { param($msg) Write-Host "[STEP] $msg" -ForegroundColor Cyan }

function Get-LatestVersion {
    try {
        $response = Invoke-RestMethod "https://api.github.com/repos/$Repo/releases/latest" -UseBasicParsing
        return $response.tag_name -replace 'v', ''
    } catch {
        Write-Warn "Could not fetch latest version, using default: 1.1.0"
        return "1.1.0"
    }
}

function Get-Architecture {
    $arch = $env:PROCESSOR_ARCHITECTURE
    switch ($arch) {
        "AMD64" { return "amd64" }
        "ARM64" { return "arm64" }
        default { return "amd64" }
    }
}

function Generate-Password {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes) -replace '[/+]', '' | Select-Object -First 16
}

function Install-Binary {
    param($ver, $os, $arch)

    $ext = ".zip"
    $filename = "guardianwaf_${ver}_${os}_${arch}${ext}"
    $downloadUrl = "https://github.com/$Repo/releases/download/v${ver}/$filename"
    $tempFile = "$env:TEMP\$filename"

    Write-Info "Downloading GuardianWAF v$ver for $os/$arch..."
    try {
        Invoke-WebRequest -Uri $downloadUrl -OutFile $tempFile -UseBasicParsing
    } catch {
        Write-Err "Download failed: $_"
        exit 1
    }

    Write-Info "Installing to $InstallDir..."

    if (-not (Test-Path $InstallDir)) {
        New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    }

    Expand-Archive -Path $tempFile -DestinationPath $InstallDir -Force
    Remove-Item $tempFile -Force

    # Add to PATH if not already
    $pathEntry = $InstallDir
    if ($env:PATH -notlike "*$pathEntry*") {
        Write-Info "Adding $InstallDir to PATH..."
        [Environment]::SetEnvironmentVariable(
            "PATH",
            "$env:PATH;$pathEntry",
            "User"
        )
        $env:PATH = "$env:PATH;$pathEntry"
    }

    Write-Info "GuardianWAF v$ver installed successfully!"
}

function New-DefaultConfig {
    Write-Info "Creating production configuration..."

    if (-not (Test-Path $ConfigDir)) {
        New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
    }

    $configPath = Join-Path $ConfigDir "guardianwaf.yaml"

    # Generate dashboard password
    $dashboardPassword = Generate-Password

    if (-not (Test-Path $configPath)) {
        @"
# GuardianWAF Configuration
# Generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
version: "1.0"

server:
  listen: ":8088"
  mode: enforce

tls:
  enabled: false
  listen: ":8443"

upstreams:
  - name: default
    targets:
      - url: "http://localhost:3000"

routes:
  - host: "*"
    upstream: default

logging:
  level: info
  format: json
  access_log: true

waf:
  detection:
    enabled: true
    block_threshold: 50
    log_threshold: 25
    detectors:
      - sqli
      - xss
      - lfi
      - cmdi
      - xxe
      - ssrf
  challenge:
    enabled: true
    difficulty: 20
  bot_detection:
    enabled: true
    mode: block
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst: 20
    auto_ban: true
    ban_duration: 15m

ipacl:
  enabled: true

cors:
  enabled: true
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - "*"
  max_age: 86400

ato:
  enabled: true
  brute_force:
    enabled: true
    max_attempts: 5
    window: 10m
    ban_duration: 30m

alerting:
  enabled: false

docker:
  enabled: false

dashboard:
  enabled: true
  listen: ":9443"
  username: "admin"
  # password: "$dashboardPassword"  # Uncomment and set securely in production

health:
  enabled: true
  path: "/healthz"

metrics:
  enabled: true
  path: "/metrics"

mcp:
  enabled: true
"@ | Out-File -FilePath $configPath -Encoding UTF8

        Write-Info "Config created at $configPath"
    } else {
        Write-Warn "Config already exists at $configPath"
    }

    Write-Warn "Dashboard password generated: $dashboardPassword"
    Write-Warn "IMPORTANT: Save this password! Set it via GWAF_DASHBOARD_PASSWORD env or update config."
}

function Install-Docker {
    Write-Info "Installing GuardianWAF via Docker..."

    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        Write-Err "Docker is not installed. Please install Docker Desktop first."
        exit 1
    }

    docker pull "ghcr.io/$Repo:latest"
    Write-Info "GuardianWAF Docker image installed!"
}

function Print-Info {
    $binaryPath = Join-Path $InstallDir $BinaryName

    Write-Host ""
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host "  GuardianWAF Installed Successfully!" -ForegroundColor Cyan
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Installation Details:"
    Write-Host "  Binary:   $binaryPath"
    Write-Host "  Config:   $ConfigDir\guardianwaf.yaml"
    Write-Host ""
    Write-Host "Quick Start:"
    Write-Host "  # Start GuardianWAF:"
    Write-Host "  & guardianwaf.exe serve -c `"$ConfigDir\guardianwaf.yaml`""
    Write-Host ""
    Write-Host "  # Docker:"
    Write-Host "  docker run -d -p 8088:8088 -p 9443:9443 ghcr.io/$Repo:latest"
    Write-Host ""
    Write-Host "Access:"
    Write-Host "  Dashboard: http://localhost:9443"
    Write-Host "  Proxy:      http://localhost:8088"
    Write-Host "  Health:     http://localhost:8088/healthz"
    Write-Host "  Metrics:    http://localhost:8088/metrics"
    Write-Host ""
    Write-Host "Commands:"
    Write-Host "  guardianwaf.exe serve         # Start WAF"
    Write-Host "  guardianwaf.exe check         # Test request"
    Write-Host "  guardianwaf.exe validate      # Validate config"
    Write-Host "  guardianwaf.exe version       # Show version"
    Write-Host ""
}

# Main
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  GuardianWAF Installation Script" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

if (-not $Version) {
    $Version = Get-LatestVersion
}

$os = "windows"
$arch = Get-Architecture

Write-Info "Version: $Version"
Write-Info "OS/Arch: $os/$arch"
Write-Info "Install type: $InstallType"
Write-Host ""

switch ($InstallType) {
    "docker" { Install-Docker }
    "binary" {
        Install-Binary -ver $Version -os $os -arch $arch
        New-DefaultConfig
    }
}

Print-Info
