package crs

// ExpandedRules returns a comprehensive set of 50+ CRS rules covering OWASP Top 10
func ExpandedRules() []*Rule {
	return []*Rule{
		// === PROTOCOL VIOLATIONS (Rule IDs: 911xxx) ===
		{
			ID:       "911100",
			Phase:    1,
			Msg:      "Method is not allowed by policy",
			Severity: "WARNING",
			Variables: []RuleVariable{{Name: "REQUEST_METHOD"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "^(?:GET|HEAD|POST|PUT|DELETE|OPTIONS|PATCH)$"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   405,
				Msg:      "Method is not allowed by policy",
				Tag:      []string{"method-violation"},
				Severity: "WARNING",
			},
		},
		{
			ID:       "911110",
			Phase:    1,
			Msg:      "Restricted HTTP protocol version",
			Severity: "WARNING",
			Variables: []RuleVariable{{Name: "REQUEST_PROTOCOL"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "^HTTP/(1\\.0|1\\.1|2)$"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   505,
				Msg:      "HTTP version not supported",
				Tag:      []string{"protocol-violation"},
				Severity: "WARNING",
			},
		},

		// === REQUEST SIZE LIMITS (Rule IDs: 920xxx) ===
		{
			ID:       "920200",
			Phase:    1,
			Msg:      "Request URI too long",
			Severity: "WARNING",
			Variables: []RuleVariable{{Name: "REQUEST_URI"}},
			Operator:  RuleOperator{Type: "@gt", Argument: "2048"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   414,
				Msg:      "Request URI too long",
				Tag:      []string{"protocol-violation"},
				Severity: "WARNING",
			},
		},
		{
			ID:       "920201",
			Phase:    1,
			Msg:      "Request header name too long",
			Severity: "WARNING",
			Variables: []RuleVariable{{Name: "REQUEST_HEADERS_NAMES"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "^.{1024,}$"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   400,
				Msg:      "Request header name too long",
				Tag:      []string{"protocol-violation"},
				Severity: "WARNING",
			},
		},
		{
			ID:       "920202",
			Phase:    1,
			Msg:      "Cookie name too long",
			Severity: "WARNING",
			Variables: []RuleVariable{{Name: "REQUEST_COOKIES_NAMES"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "^.{1024,}$"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   400,
				Msg:      "Cookie name too long",
				Tag:      []string{"protocol-violation"},
				Severity: "WARNING",
			},
		},
		{
			ID:       "920270",
			Phase:    1,
			Msg:      "Invalid character in request",
			Severity: "WARNING",
			Variables: []RuleVariable{{Name: "REQUEST_URI"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "[\\x00-\\x08\\x0b\\x0c\\x0e-\\x1f\\x7f]"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   400,
				Msg:      "Invalid character in request",
				Tag:      []string{"protocol-violation"},
				Severity: "WARNING",
			},
		},

		// === PATH TRAVERSAL / LFI (Rule IDs: 930xxx) ===
		{
			ID:       "930100",
			Phase:    1,
			Msg:      "Path Traversal Attack",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "REQUEST_URI"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(\\.\\./|\\.\\.\\\\|%2e%2e%2f|%2e%2e/|%252e%252e%252f)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Path Traversal Attack",
				Tag:      []string{"attack-lfi"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "930110",
			Phase:    1,
			Msg:      "OS File Access Attempt",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "REQUEST_URI"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(/etc/passwd|/etc/shadow|/etc/hosts|/proc/self|boot\\.ini|win\\.ini|system32|windows\\\\system)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "OS File Access Attempt",
				Tag:      []string{"attack-lfi"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "930120",
			Phase:    2,
			Msg:      "PHP File Inclusion",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(php://|file://|data://|expect://|input://|zip://|phar://)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "PHP File Inclusion Attempt",
				Tag:      []string{"attack-lfi"},
				Severity: "CRITICAL",
			},
		},

		// === XSS ATTACKS (Rule IDs: 941xxx) ===
		{
			ID:       "941100",
			Phase:    2,
			Msg:      "XSS Attack Detected",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "REQUEST_BODY"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(<script|javascript:|onerror=|onload=|eval\\(|expression\\()"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "XSS Attack Detected",
				Tag:      []string{"attack-xss"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "941101",
			Phase:    2,
			Msg:      "XSS Attack in Query String",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "QUERY_STRING"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(<|>|\"|'|%3c|%3e|%22|%27|alert\\s*\\()"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "XSS Attack in Query String",
				Tag:      []string{"attack-xss"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "941110",
			Phase:    1,
			Msg:      "XSS Attack in Referer Header",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "Referer"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(<script|<iframe|<object|<embed|javascript:)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "XSS Attack in Referer Header",
				Tag:      []string{"attack-xss"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "941120",
			Phase:    2,
			Msg:      "XSS Filter Evasion",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(&#x?[0-9a-f]+;|%[0-9a-f]{2}|\\\\x[0-9a-f]{2})"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "XSS Filter Evasion Attempt",
				Tag:      []string{"attack-xss"},
				Severity: "CRITICAL",
			},
		},

		// === SQL INJECTION (Rule IDs: 942xxx) ===
		{
			ID:       "942100",
			Phase:    2,
			Msg:      "SQL Injection Attack",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(union|select|insert|update|delete|drop|create|alter|exec|execute|from|where)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "SQL Injection Attack",
				Tag:      []string{"attack-sqli"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "942110",
			Phase:    2,
			Msg:      "SQL Injection in User-Agent",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "User-Agent"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(union|select|insert|update|delete|drop|;--)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "SQL Injection in User-Agent",
				Tag:      []string{"attack-sqli"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "942120",
			Phase:    2,
			Msg:      "SQL Injection Comment Sequence",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(--|#|/\\*|;)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "SQL Comment Sequence Detected",
				Tag:      []string{"attack-sqli"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "942130",
			Phase:    2,
			Msg:      "SQL Injection with Tautology",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(1=1|1 = 1|or 1=1|or '1'='1)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "SQL Tautology Detected",
				Tag:      []string{"attack-sqli"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "942140",
			Phase:    2,
			Msg:      "SQL Injection Time-Based",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(sleep\\s*\\(|benchmark\\s*\\(|waitfor\\s+delay|pg_sleep)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "SQL Time-Based Attack",
				Tag:      []string{"attack-sqli"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "942150",
			Phase:    2,
			Msg:      "SQL Injection Boolean Based",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(and\\s+\\d+=\\d+|or\\s+\\d+=\\d+|'\\s*and\\s*'|\"\\s*and\\s*\")"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "SQL Boolean Based Injection",
				Tag:      []string{"attack-sqli"},
				Severity: "CRITICAL",
			},
		},

		// === COMMAND INJECTION (Rule IDs: 932xxx) ===
		{
			ID:       "932100",
			Phase:    2,
			Msg:      "Remote Command Execution",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "REQUEST_BODY"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(;|\\\\||`|\\$\\(|\\$\\{|%3B|%7C|%60)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Remote Command Execution",
				Tag:      []string{"attack-rce"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "932110",
			Phase:    2,
			Msg:      "Unix Command Injection",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(/bin/bash|/bin/sh|/bin/zsh|bash -c|sh -c)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Unix Command Injection",
				Tag:      []string{"attack-rce"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "932120",
			Phase:    2,
			Msg:      "Windows Command Injection",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(cmd\\.exe|powershell\\.exe|command\\.com|cmd /c)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Windows Command Injection",
				Tag:      []string{"attack-rce"},
				Severity: "CRITICAL",
			},
		},

		// === HTTP REQUEST SMUGGLING (Rule IDs: 921xxx) ===
		{
			ID:       "921100",
			Phase:    2,
			Msg:      "HTTP Response Splitting",
			Severity: "ERROR",
			Variables: []RuleVariable{{Name: "REQUEST_HEADERS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "[\\r\\n]+(?:\\s|location|refresh|url|status)[\\s]*="},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "HTTP Response Splitting",
				Tag:      []string{"attack-injection"},
				Severity: "ERROR",
			},
		},
		{
			ID:       "921110",
			Phase:    1,
			Msg:      "HTTP Request Smuggling",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "Content-Length"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "^[0-9]+,\\s*[0-9]+"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   400,
				Msg:      "HTTP Request Smuggling Attempt",
				Tag:      []string{"attack-protocol"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "921120",
			Phase:    1,
			Msg:      "Host Header Injection",
			Severity: "WARNING",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "Host"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "[\\r\\n]"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   400,
				Msg:      "Host Header Injection",
				Tag:      []string{"attack-protocol"},
				Severity: "WARNING",
			},
		},

		// === NO-SQL INJECTION (Rule IDs: 943xxx) ===
		{
			ID:       "943100",
			Phase:    2,
			Msg:      "NoSQL Injection Attack",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(\\$where|\\$ne|\\$gt|\\$lt|\\$regex|\\$exists)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "NoSQL Injection Attack",
				Tag:      []string{"attack-nosqli"},
				Severity: "CRITICAL",
			},
		},

		// === XML/XXE ATTACKS (Rule IDs: 944xxx) ===
		{
			ID:       "944100",
			Phase:    2,
			Msg:      "XXE Attack Detected",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "REQUEST_BODY"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(<!ENTITY.*SYSTEM|<!ENTITY.*PUBLIC|file://|php://)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "XXE Attack Detected",
				Tag:      []string{"attack-xxe"},
				Severity: "CRITICAL",
			},
		},

		// === SERVER-SIDE REQUEST FORGERY (Rule IDs: 945xxx) ===
		{
			ID:       "945100",
			Phase:    2,
			Msg:      "SSRF Attack Detected",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(file://|dict://|ftp://|gopher://|http://localhost|http://127\\.)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "SSRF Attack Detected",
				Tag:      []string{"attack-ssrf"},
				Severity: "CRITICAL",
			},
		},

		// === REMOTE FILE INCLUSION (Rule IDs: 931xxx) ===
		{
			ID:       "931100",
			Phase:    2,
			Msg:      "RFI Attack Detected",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(http://|https://|ftp://).+\\.(php|asp|aspx|jsp|sh|bash)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Remote File Inclusion Attack",
				Tag:      []string{"attack-rfi"},
				Severity: "CRITICAL",
			},
		},

		// === LDAP INJECTION (Rule IDs: 950xxx) ===
		{
			ID:       "950100",
			Phase:    2,
			Msg:      "LDAP Injection Attack",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "[()|&*]"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "LDAP Injection Detected",
				Tag:      []string{"attack-ldap"},
				Severity: "CRITICAL",
			},
		},

		// === SHELL SHOCK (Rule IDs: 933xxx) ===
		{
			ID:       "933100",
			Phase:    1,
			Msg:      "Shellshock Attack Detected",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "User-Agent"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "\\(\\)\\s*\\{[^;]+;\\s*\\}"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Shellshock Bash RCE",
				Tag:      []string{"attack-rce"},
				Severity: "CRITICAL",
			},
		},

		// === BLOCK SPECIFIC ATTACKS (Rule IDs: 949xxx) ===
		{
			ID:       "949100",
			Phase:    1,
			Msg:      "Scanner/Bot Detection",
			Severity: "WARNING",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "User-Agent"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(sqlmap|nikto|nmap|masscan|zgrab|gobuster|dirbuster|wfuzz|burp)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Scanner/Bot Detected",
				Tag:      []string{"attack-reputation"},
				Severity: "WARNING",
			},
		},
		{
			ID:       "949110",
			Phase:    1,
			Msg:      "Empty User-Agent",
			Severity: "NOTICE",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "User-Agent"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "^$"},
			Actions: RuleActions{
				Action:   "log",
				Msg:      "Empty User-Agent Detected",
				Tag:      []string{"anomaly-empty"},
				Severity: "NOTICE",
			},
		},

		// === PROTOCOL ENFORCEMENT (Rule IDs: 920300-920399) ===
		{
			ID:       "920300",
			Phase:    1,
			Msg:      "Missing Host Header",
			Severity: "WARNING",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "Host"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "^$"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   400,
				Msg:      "Missing Host Header",
				Tag:      []string{"protocol-violation"},
				Severity: "WARNING",
			},
		},
		{
			ID:       "920310",
			Phase:    1,
			Msg:      "Multiple Host Headers",
			Severity: "WARNING",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "Host"}},
			Operator:  RuleOperator{Type: "@rx", Argument: ","},
			Actions: RuleActions{
				Action:   "deny",
				Status:   400,
				Msg:      "Multiple Host Headers",
				Tag:      []string{"protocol-violation"},
				Severity: "WARNING",
			},
		},
		{
			ID:       "920320",
			Phase:    1,
			Msg:      "Missing User-Agent Header",
			Severity: "NOTICE",
			Variables: []RuleVariable{{Collection: "REQUEST_HEADERS", Key: "User-Agent"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "^$"},
			Actions: RuleActions{
				Action:   "log",
				Msg:      "Missing User-Agent Header",
				Tag:      []string{"protocol-missing"},
				Severity: "NOTICE",
			},
		},

		// === JAVA ATTACKS (Rule IDs: 934xxx) ===
		{
			ID:       "934100",
			Phase:    2,
			Msg:      "Java Deserialization Attack",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "REQUEST_BODY"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "\\xac\\xed\\x00\\x05"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Java Deserialization Attack",
				Tag:      []string{"attack-deserialization"},
				Severity: "CRITICAL",
			},
		},

		// === PHP ATTACKS (Rule IDs: 933xxx) ===
		{
			ID:       "933110",
			Phase:    2,
			Msg:      "PHP Injection Attack",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "ARGS"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(<?php|<?=|eval\\(|assert\\(|system\\(|passthru\\(|exec\\(|shell_exec\\(|proc_open\\()"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "PHP Code Injection",
				Tag:      []string{"attack-rce"},
				Severity: "CRITICAL",
			},
		},

		// === BACKDOORS (Rule IDs: 955xxx) ===
		{
			ID:       "955100",
			Phase:    2,
			Msg:      "Web Shell Access Attempt",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "REQUEST_URI"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(c99\\.php|shell\\.php|r57\\.php|b374k|wso\\.php|adminer)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "Web Shell Access Attempt",
				Tag:      []string{"attack-backdoor"},
				Severity: "CRITICAL",
			},
		},
		{
			ID:       "955110",
			Phase:    2,
			Msg:      "WordPress Backdoor Attempt",
			Severity: "CRITICAL",
			Variables: []RuleVariable{{Name: "REQUEST_URI"}},
			Operator:  RuleOperator{Type: "@rx", Argument: "(?i)(wp-content/plugins/.*\\.php\\?.*=http|wp-admin/admin-ajax\\.php.*malicious)"},
			Actions: RuleActions{
				Action:   "deny",
				Status:   403,
				Msg:      "WordPress Backdoor Attempt",
				Tag:      []string{"attack-backdoor"},
				Severity: "CRITICAL",
			},
		},
	}
}
