apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardianwaf
  labels:
    app: guardianwaf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guardianwaf
  template:
    metadata:
      labels:
        app: guardianwaf
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: guardianwaf
          image: ghcr.io/guardianwaf/guardianwaf:0.4.0
          args: ["serve", "-c", "/etc/guardianwaf/guardianwaf.yaml"]
          ports:
            - containerPort: 8088
              name: http
            - containerPort: 8443
              name: https
            - containerPort: 9443
              name: dashboard
          env:
            - name: GWAF_DASHBOARD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: guardianwaf-dashboard-auth
                  key: api-key
          livenessProbe:
            httpGet:
              path: /livez
              port: 8088
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8088
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: config
              mountPath: /etc/guardianwaf
              readOnly: true
            # Mount TLS certificates from cert-manager secret
            - name: tls-cert
              mountPath: /etc/tls
              readOnly: true
            - name: state
              mountPath: /var/lib/guardianwaf
            - name: state
              mountPath: /var/log/guardianwaf
              subPath: logs
      volumes:
        - name: config
          configMap:
            name: guardianwaf-config
        # TLS certificate secret (created by cert-manager)
        - name: tls-cert
          secret:
            secretName: guardianwaf-tls
            optional: false
        - name: state
          emptyDir:
            sizeLimit: 1Gi
